<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />

<meta name="viewport" content="width=device-width, initial-scale=1" />



<title>A Monte Carlo Based Test for Between-study Heterogeneity in Meta-Analysis</title>

<script>// Pandoc 2.9 adds attributes on both header and div. We remove the former (to
// be compatible with the behavior of Pandoc < 2.8).
document.addEventListener('DOMContentLoaded', function(e) {
  var hs = document.querySelectorAll("div.section[class*='level'] > :first-child");
  var i, h, a;
  for (i = 0; i < hs.length; i++) {
    h = hs[i];
    if (!/^h[1-6]$/i.test(h.tagName)) continue;  // it should be a header h1-h6
    a = h.attributes;
    while (a.length > 0) h.removeAttribute(a[0].name);
  }
});
</script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>



<style type="text/css">body {
background-color: #fff;
margin: 1em auto;
max-width: 700px;
overflow: visible;
padding-left: 2em;
padding-right: 2em;
font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
font-size: 14px;
line-height: 1.35;
}
#TOC {
clear: both;
margin: 0 0 10px 10px;
padding: 4px;
width: 400px;
border: 1px solid #CCCCCC;
border-radius: 5px;
background-color: #f6f6f6;
font-size: 13px;
line-height: 1.3;
}
#TOC .toctitle {
font-weight: bold;
font-size: 15px;
margin-left: 5px;
}
#TOC ul {
padding-left: 40px;
margin-left: -1.5em;
margin-top: 5px;
margin-bottom: 5px;
}
#TOC ul ul {
margin-left: -2em;
}
#TOC li {
line-height: 16px;
}
table {
margin: 1em auto;
border-width: 1px;
border-color: #DDDDDD;
border-style: outset;
border-collapse: collapse;
}
table th {
border-width: 2px;
padding: 5px;
border-style: inset;
}
table td {
border-width: 1px;
border-style: inset;
line-height: 18px;
padding: 5px 5px;
}
table, table th, table td {
border-left-style: none;
border-right-style: none;
}
table thead, table tr.even {
background-color: #f7f7f7;
}
p {
margin: 0.5em 0;
}
blockquote {
background-color: #f6f6f6;
padding: 0.25em 0.75em;
}
hr {
border-style: solid;
border: none;
border-top: 1px solid #777;
margin: 28px 0;
}
dl {
margin-left: 0;
}
dl dd {
margin-bottom: 13px;
margin-left: 13px;
}
dl dt {
font-weight: bold;
}
ul {
margin-top: 0;
}
ul li {
list-style: circle outside;
}
ul ul {
margin-bottom: 0;
}
pre, code {
background-color: #f7f7f7;
border-radius: 3px;
color: #333;
white-space: pre-wrap; 
}
pre {
border-radius: 3px;
margin: 5px 0px 10px 0px;
padding: 10px;
}
pre:not([class]) {
background-color: #f7f7f7;
}
code {
font-family: Consolas, Monaco, 'Courier New', monospace;
font-size: 85%;
}
p > code, li > code {
padding: 2px 0px;
}
div.figure {
text-align: center;
}
img {
background-color: #FFFFFF;
padding: 2px;
border: 1px solid #DDDDDD;
border-radius: 3px;
border: 1px solid #CCCCCC;
margin: 0 5px;
}
h1 {
margin-top: 0;
font-size: 35px;
line-height: 40px;
}
h2 {
border-bottom: 4px solid #f7f7f7;
padding-top: 10px;
padding-bottom: 2px;
font-size: 145%;
}
h3 {
border-bottom: 2px solid #f7f7f7;
padding-top: 10px;
font-size: 120%;
}
h4 {
border-bottom: 1px solid #f7f7f7;
margin-left: 8px;
font-size: 105%;
}
h5, h6 {
border-bottom: 1px solid #ccc;
font-size: 105%;
}
a {
color: #0033dd;
text-decoration: none;
}
a:hover {
color: #6666ff; }
a:visited {
color: #800080; }
a:visited:hover {
color: #BB00BB; }
a[href^="http:"] {
text-decoration: underline; }
a[href^="https:"] {
text-decoration: underline; }

code > span.kw { color: #555; font-weight: bold; } 
code > span.dt { color: #902000; } 
code > span.dv { color: #40a070; } 
code > span.bn { color: #d14; } 
code > span.fl { color: #d14; } 
code > span.ch { color: #d14; } 
code > span.st { color: #d14; } 
code > span.co { color: #888888; font-style: italic; } 
code > span.ot { color: #007020; } 
code > span.al { color: #ff0000; font-weight: bold; } 
code > span.fu { color: #900; font-weight: bold; } 
code > span.er { color: #a61717; background-color: #e3d2d2; } 
</style>




</head>

<body>




<h1 class="title toc-ignore">A Monte Carlo Based Test for Between-study Heterogeneity in Meta-Analysis</h1>



<div id="section" class="section level6">
<h6></h6>
<p>This R package mc.heterogeneity provides functions for testing between-study heterogeneity in meta-analysis of standardized mean differences (d), Fisher-transformed Pearson’s correlations (r), and natural-logarithm-transformed odds ratio (OR).</p>
<p>Inclusion of moderators is an option for researchers who are interested in measuring the between-study heterogeneity per se and exploring factors that can explain the systematic between-study heterogeneity.</p>
<p>In the following examples, we describe how to use our package mc.heterogeneity to test the between-study heterogeneity for each of the effect sizes considered in the current study. <em>Datasets</em>, <em>R codes</em>, and <em>output</em> are provided for each example so that applied researchers can easily replicate the examples and modify the codes for their own datasets.</p>
<ul>
<li><p>The three example datasets are internal datasets in our package, but researchers can load the datasets using mc.heterogeneity:::[dataset name]. In each of the example datasets, the rows correspond to studies in meta-analysis, and the columns correspond to required input for that study, which includes, but is not limited to effect size, sample size(s), and moderators.</p></li>
<li><p>The example R codes adopt the default value for some of the arguments (e.g., default nominal alpha level is 0.05). To change the defaults, use help() to see more details for each of the functions.</p></li>
<li><p>The output are formatted to have the same layout.</p></li>
</ul>
<p>We also include a “Empirical Illustration” section in the main text of the article to discuss the following examples.</p>
</div>
<div id="installation-of-the-package" class="section level2">
<h2>0. Installation of the package</h2>
<p>Install the released version of mc.heterogeneity from <a href="https://CRAN.R-project.org">CRAN</a> with:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true"></a><span class="kw">install.packages</span>(<span class="st">&quot;mc.heterogeneity&quot;</span>)</span></code></pre></div>
<p>And load the library:</p>
<pre><code>#&gt; IMPORTANT: Please note that functions in this package will soon be deprecated and replaced by functions in package boot.heterogeneity.</code></pre>
<div id="standardized-mean-differences-d" class="section level3">
<h3>1. Standardized Mean Differences (d)</h3>
<p><code>mc.d()</code> is the function to test the between-study heterogeneity in meta-analysis of standardized mean differences (d).</p>
</div>
<div id="without-moderators" class="section level3">
<h3>1.1 Without moderators</h3>
<p>Load the example dataset <code>selfconcept</code> first:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true"></a>selfconcept &lt;-<span class="st"> </span>mc.heterogeneity<span class="op">:::</span>selfconcept</span></code></pre></div>
<p>Extract the required arguments from <code>selfconcept</code>:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true"></a><span class="co"># n1 and n2 are lists of samples sizes in two groups</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true"></a>n1 &lt;-<span class="st"> </span>selfconcept<span class="op">$</span>n1</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true"></a>n2 &lt;-<span class="st"> </span>selfconcept<span class="op">$</span>n2</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true"></a><span class="co"># g is a list of effect sizes</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true"></a>g &lt;-<span class="st"> </span>selfconcept<span class="op">$</span>g</span></code></pre></div>
<p>If <code>g</code> is a list of biased estimates of standardized mean differences in the meta-analytical study, a small-sample adjustment must be applied:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true"></a>cm &lt;-<span class="st"> </span>(<span class="dv">1-3</span><span class="op">/</span>(<span class="dv">4</span><span class="op">*</span>(n1<span class="op">+</span>n2<span class="dv">-2</span>)<span class="op">-</span><span class="dv">1</span>)) <span class="co">#correct factor to compensate for small sample bias (Hedges, 1981)</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true"></a>d &lt;-<span class="st"> </span>cm<span class="op">*</span>g</span></code></pre></div>
<p>Run the heterogeneity test using <code>mc.d()</code>:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true"></a>mc.run &lt;-<span class="st"> </span><span class="kw">mc.d</span>(n1, n2, <span class="dt">est =</span> d, <span class="dt">model =</span> <span class="st">&#39;random&#39;</span>, <span class="dt">p_cut =</span> <span class="fl">0.05</span>)</span></code></pre></div>
<p>Alternatively, such an adjustment could be performed within the function by specifying <code>adjust = TRUE</code>:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true"></a>mc.run2 &lt;-<span class="st"> </span><span class="kw">mc.d</span>(n1, n2, <span class="dt">est =</span> g, <span class="dt">model =</span> <span class="st">&#39;random&#39;</span>, <span class="dt">adjust =</span> <span class="ot">TRUE</span>, <span class="dt">p_cut =</span> <span class="fl">0.05</span>)</span></code></pre></div>
<p><code>mc.run</code> and <code>mc.run2</code> will return the same results:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true"></a>mc.run</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true"></a><span class="co">#&gt;              stat  p_value Heterogeneity</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true"></a><span class="co">#&gt; Qtest   23.391659 0.136929           n.s</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true"></a><span class="co">#&gt; mc.ML    1.610239 0.051200           n.s</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true"></a><span class="co">#&gt; mc.REML  2.037578 0.053100           n.s</span></span></code></pre></div>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true"></a>mc.run2</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true"></a><span class="co">#&gt;              stat  p_value Heterogeneity</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true"></a><span class="co">#&gt; Qtest   23.391659 0.136929           n.s</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true"></a><span class="co">#&gt; mc.ML    1.610239 0.051200           n.s</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true"></a><span class="co">#&gt; mc.REML  2.037578 0.053100           n.s</span></span></code></pre></div>
<ul>
<li><p>The first line presents the results of Q-test of a random-effects model. The Q-statistic is Q(df = 17) = 23.39 and the associated p-value is 0.137. Using a cutoff alpha level (i.e., nominal alpha level) of either 0.05 or 0.1, this statistic is n.s (not significant). The homogeneity assumption is not rejected.</p></li>
<li><p>The second line presents the results of MC-ML-LRT. The ML-LRT statistic is 1.61 and the Monte-Carlo based p-value is 0.051. The assumption of homogeneity is not rejected with an alpha level of 0.05 but will be rejected at an alpha level of 0.1.</p></li>
<li><p>The third line presents the results of MC-REML-LRT. The REML-LRT statistic is 2.04 and the Monte-Carlo based p-value is 0.053. Similar to the results of MC-ML-LR, the assumption of homogeneity is not rejected with an alpha level of 0.05 but will be rejected at an alpha level of 0.1.</p></li>
</ul>
</div>
<div id="with-moderators" class="section level3">
<h3>1.2 With moderators</h3>
<p>Load an hypothetical dataset <code>hypo_moder</code> first:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true"></a>hypo_moder &lt;-<span class="st"> </span>mc.heterogeneity<span class="op">:::</span>hypo_moder</span></code></pre></div>
<p>Three moderators (cov.z1, cov.z2, cov.z3) are included:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true"></a><span class="kw">head</span>(hypo_moder)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true"></a><span class="co">#&gt;    n1  n2          d       cov.z1      cov.z2     cov.z3</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true"></a><span class="co">#&gt; 1  59  65  0.8131324 -0.005767173  0.80418951  1.2383041</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true"></a><span class="co">#&gt; 2 166 165  1.0243732  2.404653389 -0.05710677 -0.2793463</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true"></a><span class="co">#&gt; 3  68  68  1.5954236  0.763593461  0.50360797  1.7579031</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true"></a><span class="co">#&gt; 4  44  31  0.6809888 -0.799009249  1.08576936  0.5607461</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true"></a><span class="co">#&gt; 5  98  95 -1.3017946 -1.147657009 -0.69095384 -0.4527840</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true"></a><span class="co">#&gt; 6  44  31 -1.9398508 -0.289461574 -1.28459935 -0.8320433</span></span></code></pre></div>
<p>Again, run the heterogeneity test using <code>mc.d()</code> with all moderators included in a matrix <code>mods</code> and model type specified as <code>model = &#39;mixed&#39;</code>:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true"></a>mc.run3 &lt;-<span class="st"> </span><span class="kw">mc.d</span>(<span class="dt">n1 =</span> hypo_moder<span class="op">$</span>n1, </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true"></a>                <span class="dt">n2 =</span> hypo_moder<span class="op">$</span>n2, </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true"></a>                <span class="dt">est =</span> hypo_moder<span class="op">$</span>d, </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true"></a>                <span class="dt">model =</span> <span class="st">&#39;mixed&#39;</span>, </span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true"></a>                <span class="dt">mods =</span> <span class="kw">cbind</span>(hypo_moder<span class="op">$</span>cov.z1, hypo_moder<span class="op">$</span>cov.z2, hypo_moder<span class="op">$</span>cov.z3), </span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true"></a>                <span class="dt">p_cut =</span> <span class="fl">0.05</span>)</span></code></pre></div>
<p>In the presence of moderators, the results in <code>mc.run3</code> will be different from those in <code>mc.run</code> and <code>mc.run2</code>:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true"></a>mc.run3</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true"></a><span class="co">#&gt;              stat    p_value    Heterogeneity</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true"></a><span class="co">#&gt; Qtest   31.849952 0.0008061727              sig</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true"></a><span class="co">#&gt; mc.ML    5.187700 0.0004000000              sig</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true"></a><span class="co">#&gt; mc.REML  9.283428 0.0004000000              sig</span></span></code></pre></div>
<p>In the presence of moderators, the function above tests whether the variability in the true standardized mean differences after accounting for the moderators included in the model is larger than sampling variability alone (Viechtbauer, 2010).</p>
<ul>
<li><p>In the first line, the Q-statistic is Q(df = 11) = 31.85 and the associated p-value is 0.0008. This statistic is significant (sig) at an alpha level of 0.05, meaning that the true effect sizes after accounting for the moderators are heterogeneous.</p></li>
<li><p>In the second line, the ML-LRT statistic is 5.19 and the Monte-Carlo based p-value is 0.0004. This means that the true effect sizes after accounting for the moderators are heterogeneous at an alpha level of 0.05.</p></li>
<li><p>In the third line, the REML-LRT statistic is 9.28 and the Monte-Carlo based p-value is 0.0004. This means that the true effect sizes after accounting for the moderators are heterogeneous at an alpha level of 0.05.</p></li>
</ul>
<div id="for-the-following-two-examples-fisher-transformed-pearsons-correlations-r-natural-logarithm-transformed-odds-ratio-or-no-moderators-are-included-but-one-can-simply-include-moderators-as-in-section-1.2." class="section level4">
<h4>For the following two examples (Fisher-transformed Pearson’s correlations r; Natural-logarithm-transformed odds ratio OR), no moderators are included, but one can simply include moderators as in section 1.2.</h4>
</div>
</div>
<div id="fisher-transformed-pearsons-correlations-r" class="section level3">
<h3>2. Fisher-transformed Pearson’s correlations (r)</h3>
<p><code>mc.fcor()</code> is the function to test the between-study heterogeneity in meta-analysis of Fisher-transformed Pearson’s correlations (r).</p>
<p>Load the example dataset <code>sensation</code> first:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true"></a>sensation &lt;-<span class="st"> </span>mc.heterogeneity<span class="op">:::</span>sensation</span></code></pre></div>
<p>Extract the required arguments from <code>sensation</code>:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true"></a><span class="co"># n is a list of samples sizes</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true"></a>n &lt;-<span class="st"> </span>sensation<span class="op">$</span>n</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true"></a><span class="co"># Pearson&#39;s correlation</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true"></a>r &lt;-<span class="st"> </span>sensation<span class="op">$</span>r</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true"></a><span class="co"># Fisher&#39;s Transformation</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true"></a>z &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">/</span><span class="dv">2</span><span class="op">*</span><span class="kw">log</span>((<span class="dv">1</span><span class="op">+</span>r)<span class="op">/</span>(<span class="dv">1</span><span class="op">-</span>r))</span></code></pre></div>
<p>Run the heterogeneity test using <code>mc.fcor()</code>:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true"></a>mc.run &lt;-<span class="st"> </span><span class="kw">mc.fcor</span>(n, z, <span class="dt">model =</span> <span class="st">&#39;random&#39;</span>, <span class="dt">p_cut =</span> <span class="fl">0.05</span>)</span></code></pre></div>
<p>The test of between-study heterogeneity has the following results:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true"></a>mc.run</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true"></a><span class="co">#&gt;              stat    p_value Heterogeneity</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true"></a><span class="co">#&gt; Qtest   29.060970 0.00385868           sig</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true"></a><span class="co">#&gt; mc.ML    5.204299 0.00420000           sig</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true"></a><span class="co">#&gt; mc.REML  6.133111 0.00400000           sig</span></span></code></pre></div>
<ul>
<li><p>In the first line, the Q-statistic is Q(df = 12) = 29.06 and the associated p-value is 0.004. This statistic is significant (sig) at an alpha level of 0.05, meaning that the true effect sizes are heterogeneous.</p></li>
<li><p>In the second line, the ML-LRT statistic is 5.20 and the Monte-Carlo based p-value is 0.004. This means that the true effect sizes are heterogeneous at an alpha level of 0.05.</p></li>
<li><p>In the third line, the REML-LRT statistic is 6.13 and the Monte-Carlo based p-value is 0.0004. This means that the true effect sizes are heterogeneous at an alpha level of 0.05.</p></li>
</ul>
</div>
<div id="natural-logarithm-transformed-odds-ratio-or" class="section level3">
<h3>3. Natural-logarithm-transformed odds ratio (OR)</h3>
<p><code>mc.lnOR()</code> is the function to test the between-study heterogeneity in meta-analysis of Natural-logarithm-transformed odds ratio (OR).</p>
<p>Load the example dataset <code>smoking</code> from R package <code>HSAUR3</code>:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true"></a><span class="kw">library</span>(HSAUR3)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true"></a><span class="co">#&gt; Loading required package: tools</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true"></a><span class="kw">data</span>(smoking)</span></code></pre></div>
<p>Extract the required arguments from <code>smoking</code>:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true"></a><span class="co"># Y1: receive treatment; Y2: stop smoking</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true"></a>n_<span class="dv">00</span> &lt;-<span class="st"> </span>smoking<span class="op">$</span>tc <span class="op">-</span><span class="st"> </span>smoking<span class="op">$</span>qc  <span class="co"># not receive treatement yet not stop smoking</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true"></a>n_<span class="dv">01</span> &lt;-<span class="st"> </span>smoking<span class="op">$</span>qc <span class="co"># not receive treatement but stop smoking</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true"></a>n_<span class="dv">10</span> &lt;-<span class="st"> </span>smoking<span class="op">$</span>tt <span class="op">-</span><span class="st"> </span>smoking<span class="op">$</span>qt <span class="co"># receive treatement but not stop smoking</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true"></a>n_<span class="dv">11</span> &lt;-<span class="st"> </span>smoking<span class="op">$</span>qt <span class="co"># receive treatement and stop smoking</span></span></code></pre></div>
<p>The log odds ratios can be computed, but they are not needed by <code>mc.lnOR()</code>:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true"></a>lnOR &lt;-<span class="st"> </span><span class="kw">log</span>(n_<span class="dv">11</span><span class="op">*</span>n_<span class="dv">00</span><span class="op">/</span>n_<span class="dv">01</span><span class="op">/</span>n_<span class="dv">10</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true"></a>lnOR</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true"></a><span class="co">#&gt;  [1]  0.6151856 -0.0235305  0.5658078  0.4274440  1.0814445  0.9109288</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true"></a><span class="co">#&gt;  [7]  0.9647431  0.7103890  1.0375520 -0.1407277  0.7747272  1.7924180</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true"></a><span class="co">#&gt; [13]  1.2021192  0.3607987  0.2876821  0.2110139  1.2591392  0.1549774</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true"></a><span class="co">#&gt; [19]  1.3411739  0.2963470  0.6116721  0.3786539  0.5389965  0.7532417</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true"></a><span class="co">#&gt; [25]  0.5653138  0.3786539</span></span></code></pre></div>
<p>Run the heterogeneity test using <code>mc.lnOR()</code>:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true"></a>mc.run &lt;-<span class="st"> </span><span class="kw">mc.lnOR</span>(n_<span class="dv">00</span>, n_<span class="dv">01</span>, n_<span class="dv">10</span>, n_<span class="dv">11</span>, <span class="dt">model =</span> <span class="st">&#39;random&#39;</span>, <span class="dt">p_cut =</span> <span class="fl">0.05</span>)</span></code></pre></div>
<p>The test of between-study heterogeneity has the following results:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true"></a>mc.run</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true"></a><span class="co">#&gt;              stat    p_value Heterogeneity</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true"></a><span class="co">#&gt; Qtest   34.873957 0.09050857           n.s</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true"></a><span class="co">#&gt; mc.ML    2.557171 0.02160000           sig</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true"></a><span class="co">#&gt; mc.REML  3.071329 0.02240000           sig</span></span></code></pre></div>
<ul>
<li><p>In the first line, the Q-statistic is Q(df = 25) = 34.87 and the associated p-value is 0.091. This statistic is not significant (n.s) at an alpha level of 0.05, meaning that the assumption of homogeneity cannot be rejected.</p></li>
<li><p>In the second line, the ML-LRT statistic is 2.56 and the Monte-Carlo based p-value is 0.022. This means that the assumption of homogeneity is rejected and the true effect sizes are heterogeneous at an alpha level of 0.05.</p></li>
<li><p>In the third line, the REML-LRT statistic is 3.07 and the Monte-Carlo based p-value is 0.022. This means that the assumption of homogeneity is rejected and the true effect sizes are heterogeneous at an alpha level of 0.05.</p></li>
</ul>
</div>
</div>



<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
