# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Main function to run LME
#' @noRd
#'
init_LME <- function(Y, X, Z, maxiter = 100L, eps = 1e-4) {
    .Call('_HDJM_init_LME', PACKAGE = 'HDJM', Y, X, Z, maxiter, eps)
}

#' Main function to run HDJM given one lasso penalty
#' @noRd
#'
HDJM <- function(datalist, paralist, gvec, lam, ridge, maxiter = 100L, eps = 1e-4) {
    .Call('_HDJM_HDJM', PACKAGE = 'HDJM', datalist, paralist, gvec, lam, ridge, maxiter, eps)
}

#' Main function to run HDJM for a sequence of lasso penalties
#' @noRd
#'
HDJM_seq <- function(datalist, paralist, gvec, nlam, ridge, pmax, min_ratio = 0.001, maxiter = 100L, eps = 1e-4, UseSurvN = TRUE) {
    .Call('_HDJM_HDJM_seq', PACKAGE = 'HDJM', datalist, paralist, gvec, nlam, ridge, pmax, min_ratio, maxiter, eps, UseSurvN)
}

#' Main function to predict random effects in HDJM
#' @noRd
#'
HDJM_raneff <- function(datalist, paralist, eps = 1e-4) {
    .Call('_HDJM_HDJM_raneff', PACKAGE = 'HDJM', datalist, paralist, eps)
}

