---
title: "Develop DSMolgenisArmadillo"
output: html_vignette
vignette: >
  %\VignetteIndexEntry{Develop DSMolgenisArmadillo}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



### Testing
The test are run each time you file a pull request on github. You can run the test locally as well using the following commands:


```r
# load prerequisites
library(tibble)

# run all tests
devtools::test()
#> ✔ | F W S  OK | Context
#> ⠏ |         0 | ArmadilloConnection                                                                                       ⠴ |       126 | ArmadilloConnection                                                                                       ✔ |       191 | ArmadilloConnection
#> ⠏ |         0 | ArmadilloDriver                                                                                           ✔ |        68 | ArmadilloDriver
#> ⠏ |         0 | ArmadilloOAuth                                                                                            ✔ |        11 | ArmadilloOAuth
#> ⠏ |         0 | ArmadilloResult                                                                                           ✔ |        34 | ArmadilloResult
#> ⠏ |         0 | utils                                                                                                     ✔ |     1  28 | utils
#> 
#> ══ Results ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
#> ── Skipped tests (1) ─────────────────────────────────────────────────────────────────────────────────────────────────────
#> • I still don't get the .deparse arguments (1): 'test-utils.R:87:3'
#> 
#> [ FAIL 0 | WARN 0 | SKIP 1 | PASS 332 ]
#> 
#> 🐝 Your tests are the bee's knees 🐝
```


```r
# run all tests without stopping when tests fail
devtools::test(reporter = ProgressReporter$new(max_failures = 999999))
```


```r
# run a single test file
# make sure you have the test file open
# e.g. test-ArmadilloResult.R

devtools::test_file()
```

### Vignettes
We use vignettes to expose the usage of the package. It includes examples of regular use cases and shows you how to setup the package.

The vignettes are automatically build and you can run them locally with the following command:


```r
knitr::knit("vignettes/DSMolgenisArmadillo.Rmd.orig", output = "vignettes/DSMolgenisArmadillo.Rmd")
```

If you only want the R-output use:


```r
knitr::purl("vignettes/DSMolgenisArmadillo.Rmd.orig", output = "vignettes/DSMolgenisArmadillo.R")
```

### Tips and tricks
Some tips and tricks when you developing on DSMolgenisArmadillo

#### Authentication
You can login with basic auth when you are developing. The default credentials are username: admin and password: admin.


```r
library(DSMolgenisArmadillo)

armadillo_url <- "https://armadillo-demo.molgenis.net"

builder <- DSI::newDSLoginBuilder()

builder$append(
  server = "armadillo",
  url = armadillo_url,
  user = "admin",
  password = "tuloo5saiwaeyooS",
  driver = "ArmadilloDriver",
  table = "gecko/2_1-core-1_0/nonrep",
  profile = "xenon",
  )

login_data <- builder$build()

conns <- DSI::datashield.login(logins = login_data, assign = TRUE)
```

#### Version of the package
You can determine which version of the DSMolgenisArmadillo you are running by executing the following code:


```r
dsGetInfo(armadillo())
#> $driver.version
#> [1] '2.0.3'
```

#### Table handling
You can use several methods checking if tables in DataSHIELD. For checking existence of the tables you can use the following methods.


```r
dsHasTable(conns$armadillo, "gecko/2_1-core-1_0/nonrep")
#> [1] TRUE
dsHasTable(conns$armadillo, "gecko/1_1-outcome-1_0/nonrep")
#> [1] TRUE
```

To check the accessibility you can use the `table_status` methods.


```r
datashield.table_status(conns, "gecko/2_1-core-1_0/nonrep")
#>      server                     table accessible
#> 1 armadillo gecko/2_1-core-1_0/nonrep       TRUE
```

To check which tables are assigned you can use the `dsListTables` function.


```r
dsListTables(conns$armadillo)
#>  [1] "study1/2_1-core-1_0/nonrep"               "study1/2_1-core-1_0/yearlyrep"           
#>  [3] "study1/1_1-outcome-1_0/yearlyrep"         "gecko/2_1-core-1_0/trimesterrep"         
#>  [5] "gecko/2_1-core-1_0/nonrep"                "gecko/2_1-core-1_0/yearlyrep"            
#>  [7] "gecko/2_1-core-1_0/monthlyrep"            "gecko/1_1-outcome-1_0/nonrep"            
#>  [9] "gecko/1_1-outcome-1_0/yearlyrep"          "test/data/LT-example-dataset_long-format"
#> [11] "test/data/d"                              "trajectories/data/alspac"                
#> [13] "trajectories/data/chs"                    "trajectories/data/bib"                   
#> [15] "trajectories/data/bcg"                    "trajectories/data/d"                     
#> [17] "trajectories/data/probit"                 "inma/1_2_urban_ath_1_0/yearly_rep"       
#> [19] "inma/1_2_urban_ath_1_0/trimester_rep"     "inma/1_2_urban_ath_1_0/non_rep"          
#> [21] "inma/1_1_outcome_ath_1_0/trimester_rep"   "inma/1_1_outcome_ath_1_0/non_rep"        
#> [23] "inma/1_0_outcome_ath_1_0/trimester_rep"   "inma/1_0_outcome_ath_1_0/non_rep"        
#> [25] "longitools/testparquet/LT_example_data"   "longitools/mydata/nonrep"
```

#### Methods and packages
In DataSHIELD you can use a variety of methods and packages. To check which are avaiable you can execute the following code:

##### Available packages (serverside)
The available packages displayed by the method, are the serverside R-packages. Which means the packages available on the Armadillo.


```r
conns <- DSI::datashield.login(logins = login_data, assign = F)
dsListPackages(conns$armadillo)
#>                                              name    version
#> 1                                           abind      1.4-5
#> 2                                          admisc       0.26
#> 3                                        annotate     1.72.0
#> 4                                   AnnotationDbi     1.56.2
#> 5                                AnnotationFilter     1.18.0
#> 6                                           arrow      7.0.0
#> 7                                         askpass        1.1
#> 8                                      assertthat      0.2.1
#> 9                                       backports      1.4.1
#> 10                                         base64        2.0
#> 11                                      base64enc      0.1-3
#> 12                                       beanplot      1.3.1
#> 13                                             BH   1.78.0-0
#> 14                                      BiasedUrn       1.07
#> 15                                        Biobase     2.54.0
#> 16                                  BiocFileCache      2.2.1
#> 17                                   BiocGenerics     0.40.0
#> 18                                         BiocIO      1.4.0
#> 19                                    BiocManager    1.30.20
#> 20                                   BiocParallel     1.28.3
#> 21                                    BiocVersion     3.14.0
#> 22                                        biomaRt     2.50.3
#> 23                                     Biostrings     2.62.0
#> 24                                     biovizBase     1.42.0
#> 25                                            bit      4.0.4
#> 26                                          bit64      4.0.5
#> 27                                         bitops      1.0-7
#> 28                                           blob      1.2.3
#> 29                                           brio      1.1.3
#> 30                                          broom      0.8.0
#> 31                                       BSgenome     1.62.0
#> 32                                          bslib      0.3.1
#> 33                                     bumphunter     1.36.0
#> 34                                         cachem      1.0.6
#> 35                                      calibrate      1.7.7
#> 36                                          callr      3.7.0
#> 37                                            car     3.0-12
#> 38                                        carData      3.0-5
#> 39                                        caTools     1.18.2
#> 40                                     cellranger      1.1.0
#> 41                                      checkmate      2.0.0
#> 42                                       childsds      0.8.0
#> 43                                       circlize     0.4.14
#> 44                                            cli      3.6.1
#> 45                                          clipr      0.8.0
#> 46                                           clue     0.3-60
#> 47                                     colorspace      2.0-3
#> 48                                         config      0.3.1
#> 49                                       corrplot       0.92
#> 50                                          cpp11      0.4.2
#> 51                                         crayon      1.5.1
#> 52                                    credentials      1.3.2
#> 53                                      crosstalk      1.2.0
#> 54                                           crul      1.2.0
#> 55                                           curl      4.3.2
#> 56                                     data.table     1.14.2
#> 57                                            DBI      1.1.2
#> 58                                         dbplyr      2.1.1
#> 59                                   DelayedArray     0.20.0
#> 60                             DelayedMatrixStats     1.16.0
#> 61                                          Deriv      4.1.3
#> 62                                           desc      1.4.1
#> 63                                         DESeq2     1.34.0
#> 64                                      dichromat      2.0-0
#> 65                                        diffobj      0.3.5
#> 66                                         digest     0.6.29
#> 67                                        DNAcopy     1.68.0
#> 68                                         docopt      0.7.1
#> 69                                          doRNG      1.8.2
#> 70                                          dplyr      1.1.2
#> 71                                         dsBase      6.3.0
#> 72                                     dsExposome      2.0.9
#> 73                                    dsMediation      0.0.3
#> 74                                      dsMTLBase      0.9.9
#> 75                                        dsOmics   1.0.18-2
#> 76                                     dsSurvival      2.1.3
#> 77                                             DT       0.22
#> 78                                         dtplyr      1.2.1
#> 79                                          edgeR     3.36.0
#> 80                                        elastic      1.2.0
#> 81                                        ellipse      0.4.2
#> 82                                       ellipsis      0.3.2
#> 83                                      ensembldb     2.18.4
#> 84                                       evaluate       0.15
#> 85                                     FactoMineR        2.4
#> 86                                        fANCOVA      0.6-1
#> 87                                          fansi      1.0.4
#> 88                                         farver      2.1.0
#> 89                                        fastICA      1.2-3
#> 90                                        fastmap      1.1.0
#> 91                   FDb.InfiniumMethylation.hg19      2.2.0
#> 92                                       filelock      1.0.2
#> 93                                     flashClust     1.01-2
#> 94                                        forcats      0.5.1
#> 95                                        foreach      1.5.2
#> 96                                          forge      0.2.0
#> 97                                        formatR       1.12
#> 98                                        Formula      1.2-4
#> 99                                  formula.tools      1.7.1
#> 100                                            fs      1.5.2
#> 101                                 futile.logger      1.4.3
#> 102                                futile.options      1.0.1
#> 103                                        gamlss      5.4-1
#> 104                                   gamlss.data      6.0-2
#> 105                                   gamlss.dist      6.0-3
#> 106                                        gargle      1.2.0
#> 107                                        gdsfmt     1.30.0
#> 108                                    genefilter     1.76.0
#> 109                                   geneplotter     1.72.0
#> 110                                      generics      0.1.3
#> 111                                       GENESIS     2.24.2
#> 112                                  GenomeInfoDb     1.30.1
#> 113                              GenomeInfoDbData      1.2.7
#> 114                             GenomicAlignments     1.30.0
#> 115                               GenomicFeatures     1.46.5
#> 116                                 GenomicRanges     1.46.1
#> 117                                      GEOquery     2.62.2
#> 118                                       ggplot2      3.3.5
#> 119                                       ggrepel      0.9.1
#> 120                                        glmnet      4.1-4
#> 121                                 GlobalOptions      0.1.2
#> 122                                       globals     0.14.0
#> 123                                          glue      1.6.2
#> 124                                           gmm      1.6-6
#> 125                                         GO.db     3.14.0
#> 126                                   googledrive      2.0.0
#> 127                                 googlesheets4      1.0.0
#> 128                                        gplots      3.1.1
#> 129                                     gridExtra        2.3
#> 130                                        gtable      0.3.0
#> 131                                        gtools      3.9.2
#> 132                                          Gviz     1.38.4
#> 133                                   GWASExactHW       1.01
#> 134                                     GWASTools     1.40.0
#> 135                                         haven      2.5.0
#> 136                                     HDF5Array     1.22.1
#> 137                                         highr        0.9
#> 138                                         Hmisc      4.7-0
#> 139                                           hms      1.1.1
#> 140                                     htmlTable      2.4.0
#> 141                                     htmltools      0.5.2
#> 142                                   htmlwidgets      1.5.4
#> 143                                      httpcode      0.3.0
#> 144                                          httr      1.4.2
#> 145                                           ids      1.0.1
#> 146                                        igraph      1.3.1
#> 147  IlluminaHumanMethylation450kanno.ilmn12.hg19      0.6.0
#> 148          IlluminaHumanMethylation450kmanifest      0.4.0
#> 149 IlluminaHumanMethylationEPICanno.ilm10b4.hg19      0.6.0
#> 150          IlluminaHumanMethylationEPICmanifest      0.3.0
#> 151                                    illuminaio     0.36.0
#> 152                                        impute     1.68.0
#> 153                                    imputeLCMD        2.0
#> 154                                       IRanges     2.28.0
#> 155                                       isoband      0.2.5
#> 156                                          isva        1.9
#> 157                                     iterators     1.0.14
#> 158                                          JADE      2.0-3
#> 159                                          jpeg      0.1-9
#> 160                                           jqr      1.2.3
#> 161                                     jquerylib      0.1.4
#> 162                                       jsonify      1.2.1
#> 163                                      jsonlite      1.8.0
#> 164                                      KEGGREST     1.34.0
#> 165                                         knitr       1.38
#> 166                                      labeling      0.4.2
#> 167                                      lambda.r      1.2.4
#> 168                                         later      1.3.0
#> 169                                  latticeExtra     0.6-29
#> 170                                      lazyeval      0.2.2
#> 171                                         leaps        3.1
#> 172                                     lifecycle      1.0.3
#> 173                                         limma     3.50.3
#> 174                                       littler     0.3.18
#> 175                                          lme4     1.1-29
#> 176                                        lmtest     0.9-40
#> 177                                        lobstr      1.1.1
#> 178                                        locfit    1.5-9.5
#> 179                                       logistf     1.24.1
#> 180                                       lpSolve     5.6.15
#> 181                                           lsr      0.5.2
#> 182                                     lubridate      1.8.0
#> 183                                      magrittr      2.0.3
#> 184                                    MALDIquant       1.21
#> 185                                      maptools      1.1-4
#> 186                                MatrixGenerics      1.6.0
#> 187                                  MatrixModels      0.5-0
#> 188                                   matrixStats     0.62.0
#> 189                                        mclust      5.4.9
#> 190                                          MEAL     1.24.0
#> 191                                       medflex      0.6-7
#> 192                                     mediation      4.5.0
#> 193                                       memoise      2.0.1
#> 194                                     methylumi     2.40.1
#> 195                                          mice     3.14.0
#> 196                                          mime       0.12
#> 197                                         minfi     1.40.0
#> 198                                         minqa      1.2.4
#> 199                                    missMethyl     1.28.0
#> 200                                        modelr      0.1.8
#> 201                                MolgenisRserve      0.1.2
#> 202                                     mongolite      2.6.1
#> 203                                      multcomp     1.4-18
#> 204                                  MultiDataSet     1.22.0
#> 205                                      multtest     2.50.0
#> 206                                       munsell      0.5.0
#> 207                                       mvtnorm      1.1-3
#> 208                                        nloptr      2.0.0
#> 209                                         nodbi      0.7.0
#> 210                                       nor1mix      1.3-0
#> 211                                          norm   1.0-10.0
#> 212                                      numDeriv 2016.8-1.1
#> 213                                       openssl      2.0.0
#> 214                                operator.tools      1.6.3
#> 215                                  org.Hs.eg.db     3.14.0
#> 216                                      pbkrtest      0.5.1
#> 217                                    pcaMethods     1.86.0
#> 218                                       permute      0.9-7
#> 219                                        pillar      1.9.0
#> 220                                     pkgconfig      2.0.3
#> 221                                       pkgload      1.2.4
#> 222                                         plogr      0.2.0
#> 223                                          plyr      1.8.7
#> 224                                           png      0.1-7
#> 225                                       polycor      0.8-1
#> 226                                        praise      1.0.0
#> 227                                preprocessCore     1.56.0
#> 228                                   prettyunits      1.1.1
#> 229                                      processx      3.5.3
#> 230                                      progress      1.2.2
#> 231                                      promises    1.2.0.1
#> 232                                  ProtGenerics     1.26.0
#> 233                                          pryr      0.1.5
#> 234                                            ps      1.7.5
#> 235                                         purrr      0.3.4
#> 236                                      purrrlyr      0.0.8
#> 237                                         qqman      0.1.8
#> 238                                      quadprog      1.5-8
#> 239                                      quantreg       5.88
#> 240                                   quantsmooth     1.60.0
#> 241                                        qvalue     2.26.0
#> 242                                   R.methodsS3      1.8.1
#> 243                                          R.oo     1.24.0
#> 244                                       R.utils     2.11.0
#> 245                                          r2d3      0.2.6
#> 246                                            R6      2.5.1
#> 247                                          RANN      2.6.1
#> 248                                    rapidjsonr      1.2.0
#> 249                                      rappdirs      0.3.3
#> 250                                  RColorBrewer      1.1-3
#> 251                                          Rcpp    1.0.8.3
#> 252                                 RcppArmadillo 0.11.0.0.0
#> 253                                     RcppEigen  0.3.3.9.2
#> 254                                         RCurl   1.98-1.6
#> 255                                         readr      2.1.2
#> 256                                        readxl      1.4.0
#> 257                                     regmedint      1.0.0
#> 258                                       rematch      1.0.1
#> 259                                      rematch2      2.1.2
#> 260                                       remotes      2.4.2
#> 261                                        reprex      2.0.1
#> 262                                       reshape      0.8.9
#> 263                                      reshape2      1.4.4
#> 264                                     resourcer      1.4.0
#> 265                                      restfulr     0.0.13
#> 266                                     rexposome     1.16.0
#> 267                                         rhdf5     2.38.1
#> 268                                  rhdf5filters      1.6.0
#> 269                                      Rhdf5lib     1.16.0
#> 270                                       Rhtslib     1.26.0
#> 271                                         rjson     0.2.21
#> 272                                         rlang      1.1.1
#> 273                                      RMariaDB      1.2.1
#> 274                                     rmarkdown       2.13
#> 275                                      rngtools      1.5.2
#> 276                                     RPostgres      1.4.3
#> 277                                       RPresto      1.3.7
#> 278                                     rprojroot      2.0.3
#> 279                                     Rsamtools     2.10.0
#> 280                                      RSpectra     0.16-0
#> 281                                       RSQLite     2.2.12
#> 282                                    rstudioapi       0.13
#> 283                                   rtracklayer     1.54.0
#> 284                                           ruv    0.9.7.1
#> 285                                         rvest      1.0.2
#> 286                                     S4Vectors     0.32.4
#> 287                                      sandwich      3.0-1
#> 288                                          sass      0.4.1
#> 289                                        scales      1.2.0
#> 290                                 scatterplot3d     0.3-41
#> 291                                        scrime      1.3.5
#> 292                                       selectr      0.4-2
#> 293                                      SeqArray     1.34.0
#> 294                                   SeqVarTools     1.32.0
#> 295                                         shape      1.4.6
#> 296                                      siggenes     1.68.0
#> 297                                      SmartSVA      0.1.3
#> 298                                          snow      0.4-4
#> 299                                     SNPRelate     1.28.0
#> 300                                          sofa      0.4.0
#> 301                                            sp      1.4-7
#> 302                                      sparklyr      1.7.5
#> 303                                       SparseM       1.81
#> 304                             sparseMatrixStats      1.6.0
#> 305                                           ssh      0.8.0
#> 306                                       statmod     1.4.36
#> 307                                       stringi      1.7.6
#> 308                                       stringr      1.4.0
#> 309                          SummarizedExperiment     1.24.0
#> 310                                           sva     3.42.0
#> 311                                           sys        3.4
#> 312                                      testthat      3.1.3
#> 313                                       TH.data      1.1-0
#> 314                                        tibble      3.2.1
#> 315                                         tidyr      1.2.0
#> 316                                    tidyselect      1.2.0
#> 317                                     tidyverse      1.3.1
#> 318                                       tinytex       0.38
#> 319                                      tmvtnorm        1.5
#> 320                                     triebeard      0.3.0
#> 321             TxDb.Hsapiens.UCSC.hg19.knownGene      3.2.2
#> 322                                          tzdb      0.3.0
#> 323                                      urltools      1.7.3
#> 324                                          utf8      1.2.3
#> 325                                          uuid      1.1-0
#> 326                             VariantAnnotation     1.40.0
#> 327                                         vctrs      0.6.2
#> 328                                         vegan      2.6-2
#> 329                                          VGAM      1.1-6
#> 330                                       viridis      0.6.2
#> 331                                   viridisLite      0.4.0
#> 332                                         vroom      1.5.7
#> 333                                         waldo      0.4.0
#> 334                                         withr      2.5.0
#> 335                                           wkb      0.4-0
#> 336                                          xfun       0.30
#> 337                                           XML   3.99-0.9
#> 338                                          xml2      1.3.3
#> 339                                        xtable      1.8-4
#> 340                                       XVector     0.34.0
#> 341                                          yaml      2.3.5
#> 342                                      zlibbioc     1.40.0
#> 343                                           zoo     1.8-10
#> 344                                          base      4.1.3
#> 345                                          boot     1.3-28
#> 346                                         class     7.3-20
#> 347                                       cluster      2.1.2
#> 348                                     codetools     0.2-18
#> 349                                      compiler      4.1.3
#> 350                                      datasets      4.1.3
#> 351                                       foreign     0.8-82
#> 352                                      graphics      4.1.3
#> 353                                     grDevices      4.1.3
#> 354                                          grid      4.1.3
#> 355                                    KernSmooth    2.23-20
#> 356                                       lattice    0.20-45
#> 357                                          MASS     7.3-55
#> 358                                        Matrix      1.4-0
#> 359                                       methods      4.1.3
#> 360                                          mgcv     1.8-39
#> 361                                          nlme    3.1-155
#> 362                                          nnet     7.3-17
#> 363                                      parallel      4.1.3
#> 364                                         rpart     4.1.16
#> 365                                       spatial     7.3-15
#> 366                                       splines      4.1.3
#> 367                                         stats      4.1.3
#> 368                                        stats4      4.1.3
#> 369                                      survival     3.2-13
#> 370                                         tcltk      4.1.3
#> 371                                         tools      4.1.3
#> 372                                         utils      4.1.3
```

##### Available methods (clientside)
These are the available methods on the Armadillo server.


```r
datashield.methods(conns = conns, type = "aggregate")
#>                        name                            value version package      type    class    server
#> 1       extractQuantilesDS1      dsBase::extractQuantilesDS1   6.3.0  dsBase aggregate function armadillo
#> 2              is.character               base::is.character    NULL    base aggregate function armadillo
#> 3        dataFrameSubsetDS1       dsBase::dataFrameSubsetDS1   6.3.0  dsBase aggregate function armadillo
#> 4                meanSdGpDS               dsBase::meanSdGpDS   6.3.0  dsBase aggregate function armadillo
#> 5             scatterPlotDS            dsBase::scatterPlotDS   6.3.0  dsBase aggregate function armadillo
#> 6                 setSeedDS                dsBase::setSeedDS   6.3.0  dsBase aggregate function armadillo
#> 7              minMaxRandDS             dsBase::minMaxRandDS   6.3.0  dsBase aggregate function armadillo
#> 8              matrixDetDS1             dsBase::matrixDetDS1   6.3.0  dsBase aggregate function armadillo
#> 9                   numNaDS                  dsBase::numNaDS   6.3.0  dsBase aggregate function armadillo
#> 10                 asListDS                 dsBase::asListDS   6.3.0  dsBase aggregate function armadillo
#> 11               is.numeric                 base::is.numeric    NULL    base aggregate function armadillo
#> 12                 gamlssDS                 dsBase::gamlssDS   6.3.0  dsBase aggregate function armadillo
#> 13                   t.test                    stats::t.test    NULL   stats aggregate function armadillo
#> 14          glmPredictDS.ag          dsBase::glmPredictDS.ag   6.3.0  dsBase aggregate function armadillo
#> 15      extractQuantilesDS2      dsBase::extractQuantilesDS2   6.3.0  dsBase aggregate function armadillo
#> 16                  is.list                    base::is.list    NULL    base aggregate function armadillo
#> 17                 lengthDS                 dsBase::lengthDS   6.3.0  dsBase aggregate function armadillo
#> 18            heatmapPlotDS            dsBase::heatmapPlotDS   6.3.0  dsBase aggregate function armadillo
#> 19                    dimDS                    dsBase::dimDS   6.3.0  dsBase aggregate function armadillo
#> 20                  is.null                    base::is.null    NULL    base aggregate function armadillo
#> 21          glmSummaryDS.ag          dsBase::glmSummaryDS.ag   6.3.0  dsBase aggregate function armadillo
#> 22                   meanDS                   dsBase::meanDS   6.3.0  dsBase aggregate function armadillo
#> 23                  tableDS                  dsBase::tableDS   6.3.0  dsBase aggregate function armadillo
#> 24                is.factor                  base::is.factor    NULL    base aggregate function armadillo
#> 25                    corDS                    dsBase::corDS   6.3.0  dsBase aggregate function armadillo
#> 26          testObjExistsDS          dsBase::testObjExistsDS   6.3.0  dsBase aggregate function armadillo
#> 27                 hetcorDS                 dsBase::hetcorDS   6.3.0  dsBase aggregate function armadillo
#> 28                isValidDS                dsBase::isValidDS   6.3.0  dsBase aggregate function armadillo
#> 29                table1DDS                dsBase::table1DDS   6.3.0  dsBase aggregate function armadillo
#> 30              asFactorDS1              dsBase::asFactorDS1   6.3.0  dsBase aggregate function armadillo
#> 31                   glmDS2                   dsBase::glmDS2   6.3.0  dsBase aggregate function armadillo
#> 32                   glmDS1                   dsBase::glmDS1   6.3.0  dsBase aggregate function armadillo
#> 33                    covDS                    dsBase::covDS   6.3.0  dsBase aggregate function armadillo
#> 34              kurtosisDS2              dsBase::kurtosisDS2   6.3.0  dsBase aggregate function armadillo
#> 35              kurtosisDS1              dsBase::kurtosisDS1   6.3.0  dsBase aggregate function armadillo
#> 36              lmerSLMADS2              dsBase::lmerSLMADS2   6.3.0  dsBase aggregate function armadillo
#> 37                     rmDS                     dsBase::rmDS   6.3.0  dsBase aggregate function armadillo
#> 38                   exists                     base::exists    NULL    base aggregate function armadillo
#> 39               metadataDS               dsBase::metadataDS   6.3.0  dsBase aggregate function armadillo
#> 40                  rangeDS                  dsBase::rangeDS   6.3.0  dsBase aggregate function armadillo
#> 41                table2DDS                dsBase::table2DDS   6.3.0  dsBase aggregate function armadillo
#> 42                     NROW                       base::NROW    NULL    base aggregate function armadillo
#> 43              scoreVectDS              dsBase::scoreVectDS   6.3.0  dsBase aggregate function armadillo
#> 44                 tapplyDS                 dsBase::tapplyDS   6.3.0  dsBase aggregate function armadillo
#> 45                 levelsDS                 dsBase::levelsDS   6.3.0  dsBase aggregate function armadillo
#> 46            densityGridDS            dsBase::densityGridDS   6.3.0  dsBase aggregate function armadillo
#> 47                 lexisDS1                 dsBase::lexisDS1   6.3.0  dsBase aggregate function armadillo
#> 48             histogramDS1             dsBase::histogramDS1   6.3.0  dsBase aggregate function armadillo
#> 49             histogramDS2             dsBase::histogramDS2   6.3.0  dsBase aggregate function armadillo
#> 50                 tableDS2                 dsBase::tableDS2   6.3.0  dsBase aggregate function armadillo
#> 51          checkNegValueDS          dsBase::checkNegValueDS   6.3.0  dsBase aggregate function armadillo
#> 52           quantileMeanDS           dsBase::quantileMeanDS   6.3.0  dsBase aggregate function armadillo
#> 53           ranksSecureDS3           dsBase::ranksSecureDS3   6.3.0  dsBase aggregate function armadillo
#> 54           ranksSecureDS1           dsBase::ranksSecureDS1   6.3.0  dsBase aggregate function armadillo
#> 55                    varDS                    dsBase::varDS   6.3.0  dsBase aggregate function armadillo
#> 56              boxPlotGGDS              dsBase::boxPlotGGDS   6.3.0  dsBase aggregate function armadillo
#> 57               colnamesDS               dsBase::colnamesDS   6.3.0  dsBase aggregate function armadillo
#> 58                     lsDS                     dsBase::lsDS   6.3.0  dsBase aggregate function armadillo
#> 59                  classDS                  dsBase::classDS   6.3.0  dsBase aggregate function armadillo
#> 60              skewnessDS2              dsBase::skewnessDS2   6.3.0  dsBase aggregate function armadillo
#> 61                   isNaDS                   dsBase::isNaDS   6.3.0  dsBase aggregate function armadillo
#> 62 listDisclosureSettingsDS dsBase::listDisclosureSettingsDS   6.3.0  dsBase aggregate function armadillo
#> 63              skewnessDS1              dsBase::skewnessDS1   6.3.0  dsBase aggregate function armadillo
#> 64             glmerSLMADS2             dsBase::glmerSLMADS2   6.3.0  dsBase aggregate function armadillo
#> 65               glmSLMADS1               dsBase::glmSLMADS1   6.3.0  dsBase aggregate function armadillo
#> 66               glmSLMADS2               dsBase::glmSLMADS2   6.3.0  dsBase aggregate function armadillo
#> 67                    aucDS                    dsBase::aucDS   6.3.0  dsBase aggregate function armadillo
#> 68                  namesDS                  dsBase::namesDS   6.3.0  dsBase aggregate function armadillo
#> 69                corTestDS                dsBase::corTestDS   6.3.0  dsBase aggregate function armadillo
#> 70                   miceDS                   dsBase::miceDS   6.3.0  dsBase aggregate function armadillo
#> 71                messageDS                dsBase::messageDS   6.3.0  dsBase aggregate function armadillo
datashield.methods(conns = conns, type = "assign")
#>                                  name                                      value version   package   type    class
#> 1                    changeRefGroupDS                   dsBase::changeRefGroupDS   6.3.0    dsBase assign function
#> 2          boxPlotGG_data_TreatmentDS         dsBase::boxPlotGG_data_TreatmentDS   6.3.0    dsBase assign function
#> 3                               absDS                              dsBase::absDS   6.3.0    dsBase assign function
#> 4                              sqrtDS                             dsBase::sqrtDS   6.3.0    dsBase assign function
#> 5                  dataFrameSubsetDS2                 dsBase::dataFrameSubsetDS2   6.3.0    dsBase assign function
#> 6                     blackBoxRanksDS                    dsBase::blackBoxRanksDS   6.3.0    dsBase assign function
#> 7                           lsplineDS                          dsBase::lsplineDS   6.3.0    dsBase assign function
#> 8                        matrixDiagDS                       dsBase::matrixDiagDS   6.3.0    dsBase assign function
#> 9                         asNumericDS                        dsBase::asNumericDS   6.3.0    dsBase assign function
#> 10                   glmSLMADS.assign                   dsBase::glmSLMADS.assign   6.3.0    dsBase assign function
#> 11                   asFactorSimpleDS                   dsBase::asFactorSimpleDS   6.3.0    dsBase assign function
#> 12                         asMatrixDS                         dsBase::asMatrixDS   6.3.0    dsBase assign function
#> 13                       matrixDetDS2                       dsBase::matrixDetDS2   6.3.0    dsBase assign function
#> 14                  matrixTransposeDS                  dsBase::matrixTransposeDS   6.3.0    dsBase assign function
#> 15                            mergeDS                            dsBase::mergeDS   6.3.0    dsBase assign function
#> 16                            cbindDS                            dsBase::cbindDS   6.3.0    dsBase assign function
#> 17                           asListDS                           dsBase::asListDS   6.3.0    dsBase assign function
#> 18                                log                                  base::log    NULL      base assign function
#> 19                           matrixDS                           dsBase::matrixDS   6.3.0    dsBase assign function
#> 20                         blackBoxDS                         dsBase::blackBoxDS   6.3.0    dsBase assign function
#> 21                     tableDS.assign                     dsBase::tableDS.assign   6.3.0    dsBase assign function
#> 22                              repDS                              dsBase::repDS   6.3.0    dsBase assign function
#> 23                                  c                           dsBase::vectorDS    NULL    dsBase assign function
#> 24                            rPoisDS                            dsBase::rPoisDS   6.3.0    dsBase assign function
#> 25                           unListDS                           dsBase::unListDS   6.3.0    dsBase assign function
#> 26                     matrixInvertDS                     dsBase::matrixInvertDS   6.3.0    dsBase assign function
#> 27                    tapplyDS.assign                    dsBase::tapplyDS.assign   6.3.0    dsBase assign function
#> 28                               nsDS                               dsBase::nsDS   6.3.0    dsBase assign function
#> 29                              seqDS                              dsBase::seqDS   6.3.0    dsBase assign function
#> 30                  lmerSLMADS.assign                  dsBase::lmerSLMADS.assign   6.3.0    dsBase assign function
#> 31                                abs                                  base::abs    NULL      base assign function
#> 32                    dataFrameFillDS                    dsBase::dataFrameFillDS   6.3.0    dsBase assign function
#> 33                           subsetDS                           dsBase::subsetDS   6.3.0    dsBase assign function
#> 34                            rNormDS                            dsBase::rNormDS   6.3.0    dsBase assign function
#> 35                     bp_standardsDS                     dsBase::bp_standardsDS   6.3.0    dsBase assign function
#> 36                     recodeLevelsDS                     dsBase::recodeLevelsDS   6.3.0    dsBase assign function
#> 37                    dataFrameSortDS                    dsBase::dataFrameSortDS   6.3.0    dsBase assign function
#> 38                           rBinomDS                           dsBase::rBinomDS   6.3.0    dsBase assign function
#> 39                                cDS                                dsBase::cDS   6.3.0    dsBase assign function
#> 40                    glmSummaryDS.as                    dsBase::glmSummaryDS.as   6.3.0    dsBase assign function
#> 41                           vectorDS                           dsBase::vectorDS   6.3.0    dsBase assign function
#> 42                               atan                                 base::atan    NULL      base assign function
#> 43                        dataFrameDS                        dsBase::dataFrameDS   6.3.0    dsBase assign function
#> 44                                sin                                  base::sin    NULL      base assign function
#> 45                        asFactorDS2                        dsBase::asFactorDS2   6.3.0    dsBase assign function
#> 46                    completeCasesDS                    dsBase::completeCasesDS   6.3.0    dsBase assign function
#> 47                       matrixMultDS                       dsBase::matrixMultDS   6.3.0    dsBase assign function
#> 48                    subsetByClassDS                    dsBase::subsetByClassDS   6.3.0    dsBase assign function
#> 49                     recodeValuesDS                     dsBase::recodeValuesDS   6.3.0    dsBase assign function
#> 50                             unlist                               base::unlist    NULL      base assign function
#> 51                            rbindDS                            dsBase::rbindDS   6.3.0    dsBase assign function
#> 52                          reShapeDS                          dsBase::reShapeDS   6.3.0    dsBase assign function
#> 53                            rUnifDS                            dsBase::rUnifDS   6.3.0    dsBase assign function
#> 54                                cos                                  base::cos    NULL      base assign function
#> 55                         elsplineDS                         dsBase::elsplineDS   6.3.0    dsBase assign function
#> 56                    igb_standardsDS                    dsBase::igb_standardsDS   6.3.0    dsBase assign function
#> 57                         as.numeric                           base::as.numeric    NULL      base assign function
#> 58                               list                                 base::list    NULL      base assign function
#> 59                        asIntegerDS                        dsBase::asIntegerDS   6.3.0    dsBase assign function
#> 60                         qlsplineDS                         dsBase::qlsplineDS   6.3.0    dsBase assign function
#> 61                           lexisDS2                           dsBase::lexisDS2   6.3.0    dsBase assign function
#> 62                            as.null                              base::as.null    NULL      base assign function
#> 63                                sum                                  base::sum    NULL      base assign function
#> 64                           lexisDS3                           dsBase::lexisDS3   6.3.0    dsBase assign function
#> 65                        asLogicalDS                        dsBase::asLogicalDS   6.3.0    dsBase assign function
#> 66                   matrixDimnamesDS                   dsBase::matrixDimnamesDS   6.3.0    dsBase assign function
#> 67                           uniqueDS                           dsBase::uniqueDS   6.3.0    dsBase assign function
#> 68                     ranksSecureDS5                     dsBase::ranksSecureDS5   6.3.0    dsBase assign function
#> 69                               asin                                 base::asin    NULL      base assign function
#> 70 boxPlotGG_data_Treatment_numericDS dsBase::boxPlotGG_data_Treatment_numericDS   6.3.0    dsBase assign function
#> 71                     ranksSecureDS4                     dsBase::ranksSecureDS4   6.3.0    dsBase assign function
#> 72                     complete.cases                      stats::complete.cases    NULL     stats assign function
#> 73                     ranksSecureDS2                     dsBase::ranksSecureDS2   6.3.0    dsBase assign function
#> 74                          getWGSRDS                          dsBase::getWGSRDS   6.3.0    dsBase assign function
#> 75                             listDS                             dsBase::listDS   6.3.0    dsBase assign function
#> 76                             attach                               base::attach    NULL      base assign function
#> 77                               acos                                 base::acos    NULL      base assign function
#> 78                    glmPredictDS.as                    dsBase::glmPredictDS.as   6.3.0    dsBase assign function
#> 79                      asCharacterDS                      dsBase::asCharacterDS   6.3.0    dsBase assign function
#> 80                                exp                                  base::exp    NULL      base assign function
#> 81                        replaceNaDS                        dsBase::replaceNaDS   6.3.0    dsBase assign function
#> 82                       rowColCalcDS                       dsBase::rowColCalcDS   6.3.0    dsBase assign function
#> 83                           sampleDS                           dsBase::sampleDS   6.3.0    dsBase assign function
#> 84                       as.character                         base::as.character    NULL      base assign function
#> 85                               sqrt                                 base::sqrt    NULL      base assign function
#> 86                 glmerSLMADS.assign                 dsBase::glmerSLMADS.assign   6.3.0    dsBase assign function
#> 87                            BooleDS                            dsBase::BooleDS   6.3.0    dsBase assign function
#> 88                     asDataMatrixDS                     dsBase::asDataMatrixDS   6.3.0    dsBase assign function
#> 89                           dmtC2SDS                           dsBase::dmtC2SDS   6.3.0    dsBase assign function
#> 90                                tan                                  base::tan    NULL      base assign function
#> 91             as.resource.data.frame          resourcer::as.resource.data.frame   1.4.0 resourcer assign function
#> 92                 as.resource.object              resourcer::as.resource.object   1.4.0 resourcer assign function
#> 93                    as.resource.tbl                 resourcer::as.resource.tbl   1.4.0 resourcer assign function
#>       server
#> 1  armadillo
#> 2  armadillo
#> 3  armadillo
#> 4  armadillo
#> 5  armadillo
#> 6  armadillo
#> 7  armadillo
#> 8  armadillo
#> 9  armadillo
#> 10 armadillo
#> 11 armadillo
#> 12 armadillo
#> 13 armadillo
#> 14 armadillo
#> 15 armadillo
#> 16 armadillo
#> 17 armadillo
#> 18 armadillo
#> 19 armadillo
#> 20 armadillo
#> 21 armadillo
#> 22 armadillo
#> 23 armadillo
#> 24 armadillo
#> 25 armadillo
#> 26 armadillo
#> 27 armadillo
#> 28 armadillo
#> 29 armadillo
#> 30 armadillo
#> 31 armadillo
#> 32 armadillo
#> 33 armadillo
#> 34 armadillo
#> 35 armadillo
#> 36 armadillo
#> 37 armadillo
#> 38 armadillo
#> 39 armadillo
#> 40 armadillo
#> 41 armadillo
#> 42 armadillo
#> 43 armadillo
#> 44 armadillo
#> 45 armadillo
#> 46 armadillo
#> 47 armadillo
#> 48 armadillo
#> 49 armadillo
#> 50 armadillo
#> 51 armadillo
#> 52 armadillo
#> 53 armadillo
#> 54 armadillo
#> 55 armadillo
#> 56 armadillo
#> 57 armadillo
#> 58 armadillo
#> 59 armadillo
#> 60 armadillo
#> 61 armadillo
#> 62 armadillo
#> 63 armadillo
#> 64 armadillo
#> 65 armadillo
#> 66 armadillo
#> 67 armadillo
#> 68 armadillo
#> 69 armadillo
#> 70 armadillo
#> 71 armadillo
#> 72 armadillo
#> 73 armadillo
#> 74 armadillo
#> 75 armadillo
#> 76 armadillo
#> 77 armadillo
#> 78 armadillo
#> 79 armadillo
#> 80 armadillo
#> 81 armadillo
#> 82 armadillo
#> 83 armadillo
#> 84 armadillo
#> 85 armadillo
#> 86 armadillo
#> 87 armadillo
#> 88 armadillo
#> 89 armadillo
#> 90 armadillo
#> 91 armadillo
#> 92 armadillo
#> 93 armadillo
```





