##########################################################################
# Copyright (c) 2023, King Abdullah University of Science and Technology
# All rights reserved.
# MPCR is an R package provided by the STSDS group at KAUST
##########################################################################

# this file is added to let R CMD build with Custom build configuration instead of using its
# main build system
all :
