# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

M_Update_Rcpp <- function(Mean, D, Uinv, Vinv, nc, weightmat, rho, lambda, C, r, mtol) {
    .Call('M_Update_Rcpp', PACKAGE = 'MatrixLDA', Mean, D, Uinv, Vinv, nc, weightmat, rho, lambda, C, r, mtol)
}

