---
title: "RTTWebClient"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{RTTWebClient}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, eval=FALSE}
library(RTTWebClient)
library(lubridate)
```

<!-- # Example of RTTWebApi methods (basic class) -->

<!-- ## Init Public(default) Client Obj (reference R class) -->
<!-- ```{r, eval=FALSE} -->
<!-- ttWebClient <- InitPublicWebClient(server = "ttlivewebapi.fxopen.com") -->
<!-- #or use InitPrivateWebClient(server = "ttlivewebapi.fxopen.com", port = 8443, id = "", key = "", secret = "") to set a private connect. Need set HMAC id, key and secret -->
<!-- ``` -->

<!-- ## Get Dividends data.table -->
<!-- ```{r, eval=FALSE} -->
<!-- print(ttWebClient$GetDividendsRawMethod()) -->
<!-- ``` -->

<!-- ## Get Symbol data.table -->
<!-- ```{r, eval=FALSE} -->
<!-- print(ttWebClient$GetSymbolsInfoRawMethod()) -->
<!-- ``` -->

<!-- ## Get BarHistory data.table -->
<!-- ```{r, eval=FALSE} -->
<!-- print(ttWebClient$GetBarRawMethod("EURUSD", "Bid","M1", round(as.double(now("UTC")) * 1000), count = -10)) -->
<!-- ``` -->

<!-- ## Get TickHistory data.table -->
<!-- ```{r, eval=FALSE} -->
<!-- print(ttWebClient$GetTicksRawMethod("EURUSD", round(as.double(now("UTC")) * 1000), count = -10)) -->
<!-- ``` -->


# Example of RTTWebApiHost (Wrapper about RTTWebClient to make request from R easy)

## Init RTTWebApiHost obj
```{r, eval=FALSE}
ttWebApiHost <- InitRTTWebApiHost(server = "ttlivewebapi.fxopen.com")
```

## Get Dividends data.table
```{r, eval=FALSE}
print(ttWebApiHost$GetDividends())
```

## Get Symbol data.table
```{r, eval=FALSE}
print(ttWebApiHost$GetSymbolsInfo())
```

## Get BarHistory data.table
```{r, eval=FALSE}
print(ttWebApiHost$GetBarsHistory("EURUSD", "Bid","M1", now("UTC") - days(1), now("UTC")))
```

## Get TicksHistory data.table
```{r, eval=FALSE}
print(ttWebApiHost$GetTickHistory("EURUSD",  now("UTC") - days(1), now("UTC")))
```

## Get Currency data.table
```{r, eval=FALSE}
print(ttWebApiHost$GetCurrencyInfo())
```
