#! /bin/sh
##########################################################################
# Copyright (c) 2023, King Abdullah University of Science and Technology
# All rights reserved.
# MPCR is an R package provided by the STSDS group at KAUST
##########################################################################

# This file is intended to be used during 'R CMD build' command to delete all unnecessary files for CRAN submission.
# Don't run this file if you're trying to run the code as a C++ module, or need to build doxygen documentation for the
# the C++ code.

rm -rf ./src/*.so*
rm -rf ./src/*.d
rm -rf ./src/*.dll
rm -rf ./.idea/
rm -rf ./cmake-build-debug
rm -rf ./bin/
rm -rf ./.git/
rm -rf ./config.sh
rm -rf ./clean_build.sh
rm -rf ./..Rcheck/
rm -rf ./benchmarks/
rm -rf ./doxygen_config
rm -rf ./prerequisites/

mv ./LICENSE.md ./LICENSE

mv ./cmake/ ./src/cmake/
mv ./CMakeLists.txt ./src/CMakeLists_inv.txt
