---
title: "List of models"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{models}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

`SSLR` contains models created by developers and wrappers of different packages such as [`RSSL`](https://CRAN.R-project.org/package=RSSL). From [`RSSL`](https://CRAN.R-project.org/package=RSSL), we use S3VM methods.

The list of models is:

* **Classification**: [`SelfTraining()`](.././reference/selfTraining.html),[`SSLRDecisionTree()`](.././reference/SSLRDecisionTree.html), [`SSLRRandomForest()`](.././reference/SSLRRandomForest.html), [`triTraining()`](.././reference/triTraining.html), [`coBC()`](.././reference/coBC.html), [`democratic()`](.././reference/democratic.html), [`EMLeastSquaresClassifierSSLR()`](.././reference/EMLeastSquaresClassifierSSLR.html), [`EMNearestMeanClassifierSSLR()`](.././reference/EMNearestMeanClassifierSSLR.html), [`EntropyRegularizedLogisticRegressionSSLR()`](.././reference/EntropyRegularizedLogisticRegressionSSLR.html), [`LaplacianSVMSSLR()`](.././reference/LaplacianSVMSSLR.html), [`LinearTSVMSSLR()`](.././reference/LinearTSVMSSLR.html), [`WellSVMSSLR()`](.././reference/WellSVMSSLR.html), [`MCNearestMeanClassifierSSLR()`](.././reference/MCNearestMeanClassifierSSLR.html), [`oneNN()`](.././reference/oneNN.html), [`setred()`](.././reference/setred.html), [`snnrce()`](.././reference/snnrce.html), [`TSVMSSLR()`](.././reference/TSVMSSLR.html), [`USMLeastSquaresClassifierSSLR()`](.././reference/USMLeastSquaresClassifierSSLR.html),
[`GRFClassifierSSLR()`](.././reference/GRFClassifierSSLR.html)


* **Regression**: [`coBC()`](.././reference/coBC.html),[`COREG()`](.././reference/COREG.html), [`SSLRDecisionTree()`](.././reference/SSLRDecisionTree.html), [`SSLRRandomForest()`](.././reference/SSLRRandomForest.html)


* **Clustering**: [`constrained_kmeans()`](.././reference/constrained_kmeans.html),
                  [`seeded_kmeans()`](.././reference/seeded_kmeans.html),
                  [`ckmeansSSLR()`](.././reference/ckmeansSSLR.html),
                  [`cclsSSLR()`](.././reference/cclsSSLR.html),
                  [`mpckmSSLR()`](.././reference/mpckmSSLR.html),
                  [`lcvqeSSLR()`](.././reference/lcvqeSSLR.html)


***NOTE***: In the [`Regression modelling`](.././articles/regression.html) section we can see more examples of use in regression tasks. 
In *Decision Tree* , *Random Forest* and *coBC* we only have examples for classification tasks.


***NOTE***: In the [`Clustering modelling`](.././articles/clustering.html) section we can see how to plot clusters with `factoextra` package.

