// Generated by rstantools.  Do not edit by hand.

/*
    postlink is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    postlink is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with postlink.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_glmMixBayes_gamma_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 53> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 28, column 2 to column 31)",
  " (in 'string', line 29, column 2 to column 18)",
  " (in 'string', line 30, column 2 to column 18)",
  " (in 'string', line 31, column 2 to column 21)",
  " (in 'string', line 32, column 2 to column 21)",
  " (in 'string', line 36, column 2 to column 29)",
  " (in 'string', line 37, column 2 to column 29)",
  " (in 'string', line 62, column 2 to column 29)",
  " (in 'string', line 64, column 4 to column 17)",
  " (in 'string', line 65, column 4 to column 71)",
  " (in 'string', line 66, column 4 to column 73)",
  " (in 'string', line 67, column 4 to column 40)",
  " (in 'string', line 63, column 17 to line 68, column 3)",
  " (in 'string', line 63, column 2 to line 68, column 3)",
  " (in 'string', line 41, column 2 to column 62)",
  " (in 'string', line 42, column 2 to column 62)",
  " (in 'string', line 44, column 4 to column 56)",
  " (in 'string', line 45, column 4 to column 56)",
  " (in 'string', line 43, column 13 to line 46, column 3)",
  " (in 'string', line 43, column 2 to line 46, column 3)",
  " (in 'string', line 47, column 2 to column 50)",
  " (in 'string', line 48, column 2 to column 50)",
  " (in 'string', line 49, column 2 to column 52)",
  " (in 'string', line 53, column 4 to line 57, column 6)",
  " (in 'string', line 51, column 17 to line 58, column 3)",
  " (in 'string', line 51, column 2 to line 58, column 3)",
  " (in 'string', line 4, column 2 to column 17)",
  " (in 'string', line 5, column 2 to column 17)",
  " (in 'string', line 6, column 18 to column 19)",
  " (in 'string', line 6, column 2 to column 23)",
  " (in 'string', line 7, column 9 to column 10)",
  " (in 'string', line 7, column 12 to column 13)",
  " (in 'string', line 7, column 2 to column 17)",
  " (in 'string', line 10, column 2 to column 27)",
  " (in 'string', line 11, column 2 to column 36)",
  " (in 'string', line 12, column 2 to column 27)",
  " (in 'string', line 13, column 2 to column 36)",
  " (in 'string', line 15, column 2 to column 22)",
  " (in 'string', line 16, column 2 to column 31)",
  " (in 'string', line 17, column 2 to column 22)",
  " (in 'string', line 18, column 2 to column 31)",
  " (in 'string', line 19, column 2 to column 33)",
  " (in 'string', line 20, column 2 to column 32)",
  " (in 'string', line 21, column 2 to column 33)",
  " (in 'string', line 22, column 2 to column 32)",
  " (in 'string', line 23, column 2 to column 34)",
  " (in 'string', line 24, column 2 to column 33)",
  " (in 'string', line 29, column 9 to column 10)",
  " (in 'string', line 30, column 9 to column 10)",
  " (in 'string', line 36, column 9 to column 10)",
  " (in 'string', line 37, column 9 to column 10)",
  " (in 'string', line 62, column 26 to column 27)"};
#include <stan_meta_header.hpp>
class model_glmMixBayes_gamma final : public model_base_crtp<model_glmMixBayes_gamma> {
private:
  int N;
  int K;
  Eigen::Matrix<double,-1,1> y_data__;
  Eigen::Matrix<double,-1,-1> X_data__;
  double prior_intercept1_mu;
  double prior_intercept1_sd;
  double prior_intercept2_mu;
  double prior_intercept2_sd;
  double prior_beta1_mu;
  double prior_beta1_sd;
  double prior_beta2_mu;
  double prior_beta2_sd;
  double prior_phi1_alpha;
  double prior_phi1_beta;
  double prior_phi2_alpha;
  double prior_phi2_beta;
  double prior_theta_alpha;
  double prior_theta_beta;
  Eigen::Map<Eigen::Matrix<double,-1,1>> y{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X{nullptr, 0, 0};
public:
  ~model_glmMixBayes_gamma() {}
  model_glmMixBayes_gamma(stan::io::var_context& context__, unsigned int
                          random_seed__ = 0, std::ostream*
                          pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_glmMixBayes_gamma_namespace::model_glmMixBayes_gamma";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 27;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 27;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 27;
      stan::math::check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 28;
      context__.validate_dims("data initialization", "K", "int",
        std::vector<size_t>{});
      K = std::numeric_limits<int>::min();
      current_statement__ = 28;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 28;
      stan::math::check_greater_or_equal(function__, "K", K, 1);
      current_statement__ = 29;
      stan::math::validate_non_negative_index("y", "N", N);
      current_statement__ = 30;
      context__.validate_dims("data initialization", "y", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      y_data__ = Eigen::Matrix<double,-1,1>::Constant(N,
                   std::numeric_limits<double>::quiet_NaN());
      new (&y) Eigen::Map<Eigen::Matrix<double,-1,1>>(y_data__.data(), N);
      {
        std::vector<local_scalar_t__> y_flat__;
        current_statement__ = 30;
        y_flat__ = context__.vals_r("y");
        current_statement__ = 30;
        pos__ = 1;
        current_statement__ = 30;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 30;
          stan::model::assign(y, y_flat__[(pos__ - 1)],
            "assigning variable y", stan::model::index_uni(sym1__));
          current_statement__ = 30;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 30;
      stan::math::check_greater_or_equal(function__, "y", y, 0);
      current_statement__ = 31;
      stan::math::validate_non_negative_index("X", "N", N);
      current_statement__ = 32;
      stan::math::validate_non_negative_index("X", "K", K);
      current_statement__ = 33;
      context__.validate_dims("data initialization", "X", "double",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(K)});
      X_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, K,
                   std::numeric_limits<double>::quiet_NaN());
      new (&X) Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_data__.data(), N, K);
      {
        std::vector<local_scalar_t__> X_flat__;
        current_statement__ = 33;
        X_flat__ = context__.vals_r("X");
        current_statement__ = 33;
        pos__ = 1;
        current_statement__ = 33;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 33;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 33;
            stan::model::assign(X, X_flat__[(pos__ - 1)],
              "assigning variable X", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 33;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 34;
      context__.validate_dims("data initialization", "prior_intercept1_mu",
        "double", std::vector<size_t>{});
      prior_intercept1_mu = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 34;
      prior_intercept1_mu = context__.vals_r("prior_intercept1_mu")[(1 - 1)];
      current_statement__ = 35;
      context__.validate_dims("data initialization", "prior_intercept1_sd",
        "double", std::vector<size_t>{});
      prior_intercept1_sd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 35;
      prior_intercept1_sd = context__.vals_r("prior_intercept1_sd")[(1 - 1)];
      current_statement__ = 35;
      stan::math::check_greater_or_equal(function__, "prior_intercept1_sd",
        prior_intercept1_sd, 0);
      current_statement__ = 36;
      context__.validate_dims("data initialization", "prior_intercept2_mu",
        "double", std::vector<size_t>{});
      prior_intercept2_mu = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 36;
      prior_intercept2_mu = context__.vals_r("prior_intercept2_mu")[(1 - 1)];
      current_statement__ = 37;
      context__.validate_dims("data initialization", "prior_intercept2_sd",
        "double", std::vector<size_t>{});
      prior_intercept2_sd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 37;
      prior_intercept2_sd = context__.vals_r("prior_intercept2_sd")[(1 - 1)];
      current_statement__ = 37;
      stan::math::check_greater_or_equal(function__, "prior_intercept2_sd",
        prior_intercept2_sd, 0);
      current_statement__ = 38;
      context__.validate_dims("data initialization", "prior_beta1_mu",
        "double", std::vector<size_t>{});
      prior_beta1_mu = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 38;
      prior_beta1_mu = context__.vals_r("prior_beta1_mu")[(1 - 1)];
      current_statement__ = 39;
      context__.validate_dims("data initialization", "prior_beta1_sd",
        "double", std::vector<size_t>{});
      prior_beta1_sd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 39;
      prior_beta1_sd = context__.vals_r("prior_beta1_sd")[(1 - 1)];
      current_statement__ = 39;
      stan::math::check_greater_or_equal(function__, "prior_beta1_sd",
        prior_beta1_sd, 0);
      current_statement__ = 40;
      context__.validate_dims("data initialization", "prior_beta2_mu",
        "double", std::vector<size_t>{});
      prior_beta2_mu = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 40;
      prior_beta2_mu = context__.vals_r("prior_beta2_mu")[(1 - 1)];
      current_statement__ = 41;
      context__.validate_dims("data initialization", "prior_beta2_sd",
        "double", std::vector<size_t>{});
      prior_beta2_sd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 41;
      prior_beta2_sd = context__.vals_r("prior_beta2_sd")[(1 - 1)];
      current_statement__ = 41;
      stan::math::check_greater_or_equal(function__, "prior_beta2_sd",
        prior_beta2_sd, 0);
      current_statement__ = 42;
      context__.validate_dims("data initialization", "prior_phi1_alpha",
        "double", std::vector<size_t>{});
      prior_phi1_alpha = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 42;
      prior_phi1_alpha = context__.vals_r("prior_phi1_alpha")[(1 - 1)];
      current_statement__ = 42;
      stan::math::check_greater_or_equal(function__, "prior_phi1_alpha",
        prior_phi1_alpha, 0);
      current_statement__ = 43;
      context__.validate_dims("data initialization", "prior_phi1_beta",
        "double", std::vector<size_t>{});
      prior_phi1_beta = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 43;
      prior_phi1_beta = context__.vals_r("prior_phi1_beta")[(1 - 1)];
      current_statement__ = 43;
      stan::math::check_greater_or_equal(function__, "prior_phi1_beta",
        prior_phi1_beta, 0);
      current_statement__ = 44;
      context__.validate_dims("data initialization", "prior_phi2_alpha",
        "double", std::vector<size_t>{});
      prior_phi2_alpha = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 44;
      prior_phi2_alpha = context__.vals_r("prior_phi2_alpha")[(1 - 1)];
      current_statement__ = 44;
      stan::math::check_greater_or_equal(function__, "prior_phi2_alpha",
        prior_phi2_alpha, 0);
      current_statement__ = 45;
      context__.validate_dims("data initialization", "prior_phi2_beta",
        "double", std::vector<size_t>{});
      prior_phi2_beta = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 45;
      prior_phi2_beta = context__.vals_r("prior_phi2_beta")[(1 - 1)];
      current_statement__ = 45;
      stan::math::check_greater_or_equal(function__, "prior_phi2_beta",
        prior_phi2_beta, 0);
      current_statement__ = 46;
      context__.validate_dims("data initialization", "prior_theta_alpha",
        "double", std::vector<size_t>{});
      prior_theta_alpha = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 46;
      prior_theta_alpha = context__.vals_r("prior_theta_alpha")[(1 - 1)];
      current_statement__ = 46;
      stan::math::check_greater_or_equal(function__, "prior_theta_alpha",
        prior_theta_alpha, 0);
      current_statement__ = 47;
      context__.validate_dims("data initialization", "prior_theta_beta",
        "double", std::vector<size_t>{});
      prior_theta_beta = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 47;
      prior_theta_beta = context__.vals_r("prior_theta_beta")[(1 - 1)];
      current_statement__ = 47;
      stan::math::check_greater_or_equal(function__, "prior_theta_beta",
        prior_theta_beta, 0);
      current_statement__ = 48;
      stan::math::validate_non_negative_index("beta1", "K", K);
      current_statement__ = 49;
      stan::math::validate_non_negative_index("beta2", "K", K);
      current_statement__ = 50;
      stan::math::validate_non_negative_index("eta1", "N", N);
      current_statement__ = 51;
      stan::math::validate_non_negative_index("eta2", "N", N);
      current_statement__ = 52;
      stan::math::validate_non_negative_index("z", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + K + K + 1 + 1;
  }
  inline std::string model_name() const final {
    return "model_glmMixBayes_gamma";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_glmMixBayes_gamma_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ theta = DUMMY_VAR__;
      current_statement__ = 1;
      theta = in__.template read_constrain_lub<local_scalar_t__,
                jacobian__>(0, 1, lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> beta1 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 2;
      beta1 = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K);
      Eigen::Matrix<local_scalar_t__,-1,1> beta2 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 3;
      beta2 = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K);
      local_scalar_t__ phi1 = DUMMY_VAR__;
      current_statement__ = 4;
      phi1 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
               lp__);
      local_scalar_t__ phi2 = DUMMY_VAR__;
      current_statement__ = 5;
      phi2 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
               lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> eta1 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      current_statement__ = 6;
      stan::model::assign(eta1, stan::math::multiply(X, beta1),
        "assigning variable eta1");
      Eigen::Matrix<local_scalar_t__,-1,1> eta2 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      current_statement__ = 7;
      stan::model::assign(eta2, stan::math::multiply(X, beta2),
        "assigning variable eta2");
      {
        current_statement__ = 15;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(
                         stan::model::rvalue(beta1, "beta1",
                           stan::model::index_uni(1)), prior_intercept1_mu,
                         prior_intercept1_sd));
        current_statement__ = 16;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(
                         stan::model::rvalue(beta2, "beta2",
                           stan::model::index_uni(1)), prior_intercept2_mu,
                         prior_intercept2_sd));
        current_statement__ = 20;
        if (stan::math::logical_gt(K, 1)) {
          current_statement__ = 17;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(
                           stan::model::rvalue(beta1, "beta1",
                             stan::model::index_min_max(2, K)),
                           prior_beta1_mu, prior_beta1_sd));
          current_statement__ = 18;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(
                           stan::model::rvalue(beta2, "beta2",
                             stan::model::index_min_max(2, K)),
                           prior_beta2_mu, prior_beta2_sd));
        }
        current_statement__ = 21;
        lp_accum__.add(stan::math::gamma_lpdf<propto__>(phi1,
                         prior_phi1_alpha, prior_phi1_beta));
        current_statement__ = 22;
        lp_accum__.add(stan::math::gamma_lpdf<propto__>(phi2,
                         prior_phi2_alpha, prior_phi2_beta));
        current_statement__ = 23;
        lp_accum__.add(stan::math::beta_lpdf<propto__>(theta,
                         prior_theta_alpha, prior_theta_beta));
        current_statement__ = 26;
        for (int n = 1; n <= N; ++n) {
          current_statement__ = 24;
          lp_accum__.add(stan::math::log_mix(theta,
                           stan::math::gamma_lpdf<false>(
                             stan::model::rvalue(y, "y",
                               stan::model::index_uni(n)), phi1, (phi1 *
                             stan::math::exp(
                               -stan::model::rvalue(eta1, "eta1",
                                  stan::model::index_uni(n))))),
                           stan::math::gamma_lpdf<false>(
                             stan::model::rvalue(y, "y",
                               stan::model::index_uni(n)), phi2, (phi2 *
                             stan::math::exp(
                               -stan::model::rvalue(eta2, "eta2",
                                  stan::model::index_uni(n)))))));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_glmMixBayes_gamma_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double theta = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      theta = in__.template read_constrain_lub<local_scalar_t__,
                jacobian__>(0, 1, lp__);
      Eigen::Matrix<double,-1,1> beta1 =
        Eigen::Matrix<double,-1,1>::Constant(K,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      beta1 = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K);
      Eigen::Matrix<double,-1,1> beta2 =
        Eigen::Matrix<double,-1,1>::Constant(K,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      beta2 = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K);
      double phi1 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      phi1 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
               lp__);
      double phi2 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 5;
      phi2 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
               lp__);
      Eigen::Matrix<double,-1,1> eta1 =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> eta2 =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(theta);
      out__.write(beta1);
      out__.write(beta2);
      out__.write(phi1);
      out__.write(phi2);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 6;
      stan::model::assign(eta1, stan::math::multiply(X, beta1),
        "assigning variable eta1");
      current_statement__ = 7;
      stan::model::assign(eta2, stan::math::multiply(X, beta2),
        "assigning variable eta2");
      if (emit_transformed_parameters__) {
        out__.write(eta1);
        out__.write(eta2);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      std::vector<int> z =
        std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 14;
      for (int n = 1; n <= N; ++n) {
        Eigen::Matrix<double,-1,1> lw =
          Eigen::Matrix<double,-1,1>::Constant(2,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 10;
        stan::model::assign(lw, (stan::math::log(theta) +
          stan::math::gamma_lpdf<false>(
            stan::model::rvalue(y, "y", stan::model::index_uni(n)), phi1,
            (phi1 *
            stan::math::exp(
              -stan::model::rvalue(eta1, "eta1", stan::model::index_uni(n)))))),
          "assigning variable lw", stan::model::index_uni(1));
        current_statement__ = 11;
        stan::model::assign(lw, (stan::math::log1m(theta) +
          stan::math::gamma_lpdf<false>(
            stan::model::rvalue(y, "y", stan::model::index_uni(n)), phi2,
            (phi2 *
            stan::math::exp(
              -stan::model::rvalue(eta2, "eta2", stan::model::index_uni(n)))))),
          "assigning variable lw", stan::model::index_uni(2));
        current_statement__ = 12;
        stan::model::assign(z,
          stan::math::categorical_rng(stan::math::softmax(lw), base_rng__),
          "assigning variable z", stan::model::index_uni(n));
      }
      current_statement__ = 8;
      stan::math::check_greater_or_equal(function__, "z", z, 1);
      current_statement__ = 8;
      stan::math::check_less_or_equal(function__, "z", z, 2);
      out__.write(z);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ theta = DUMMY_VAR__;
      current_statement__ = 1;
      theta = in__.read<local_scalar_t__>();
      out__.write_free_lub(0, 1, theta);
      Eigen::Matrix<local_scalar_t__,-1,1> beta1 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(beta1,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K),
        "assigning variable beta1");
      out__.write(beta1);
      Eigen::Matrix<local_scalar_t__,-1,1> beta2 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(beta2,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K),
        "assigning variable beta2");
      out__.write(beta2);
      local_scalar_t__ phi1 = DUMMY_VAR__;
      current_statement__ = 4;
      phi1 = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, phi1);
      local_scalar_t__ phi2 = DUMMY_VAR__;
      current_statement__ = 5;
      phi2 = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, phi2);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "theta", "double",
        std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "beta1", "double",
        std::vector<size_t>{static_cast<size_t>(K)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "beta2", "double",
        std::vector<size_t>{static_cast<size_t>(K)});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "phi1", "double",
        std::vector<size_t>{});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "phi2", "double",
        std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ theta = DUMMY_VAR__;
      current_statement__ = 1;
      theta = context__.vals_r("theta")[(1 - 1)];
      out__.write_free_lub(0, 1, theta);
      Eigen::Matrix<local_scalar_t__,-1,1> beta1 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> beta1_flat__;
        current_statement__ = 2;
        beta1_flat__ = context__.vals_r("beta1");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 2;
          stan::model::assign(beta1, beta1_flat__[(pos__ - 1)],
            "assigning variable beta1", stan::model::index_uni(sym1__));
          current_statement__ = 2;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(beta1);
      Eigen::Matrix<local_scalar_t__,-1,1> beta2 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> beta2_flat__;
        current_statement__ = 3;
        beta2_flat__ = context__.vals_r("beta2");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 3;
          stan::model::assign(beta2, beta2_flat__[(pos__ - 1)],
            "assigning variable beta2", stan::model::index_uni(sym1__));
          current_statement__ = 3;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(beta2);
      local_scalar_t__ phi1 = DUMMY_VAR__;
      current_statement__ = 4;
      phi1 = context__.vals_r("phi1")[(1 - 1)];
      out__.write_free_lb(0, phi1);
      local_scalar_t__ phi2 = DUMMY_VAR__;
      current_statement__ = 5;
      phi2 = context__.vals_r("phi2")[(1 - 1)];
      out__.write_free_lb(0, phi2);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"theta", "beta1", "beta2", "phi1",
                "phi2"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"eta1", "eta2"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"z"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(K)},
                std::vector<size_t>{static_cast<size_t>(K)},
                std::vector<size_t>{}, std::vector<size_t>{}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(N)},
             std::vector<size_t>{static_cast<size_t>(N)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(N)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "theta");
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta1" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta2" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "phi1");
    param_names__.emplace_back(std::string() + "phi2");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "eta1" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "eta2" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "z" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "theta");
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta1" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta2" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "phi1");
    param_names__.emplace_back(std::string() + "phi2");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "eta1" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "eta2" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "z" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"theta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta1\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"beta2\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"phi1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"phi2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"eta1\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"eta2\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"z\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"int\"}},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"theta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta1\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"beta2\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"phi1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"phi2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"eta1\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"eta2\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"z\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"int\"}},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((1 + K) + K) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * ((N + N));
    const size_t num_gen_quantities = emit_generated_quantities * (N);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((1 + K) + K) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * ((N + N));
    const size_t num_gen_quantities = emit_generated_quantities * (N);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_glmMixBayes_gamma_namespace::model_glmMixBayes_gamma;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_glmMixBayes_gamma_namespace::profiles__;
}
#endif
#endif
