# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' calculate baf_1d for 1 normal + 1 tumor case
#' @keywords internal
#' @export
calcll_1d_baf <- function(lrr, nrc, baf, n_baf, lprior_f_2d, rlprior_f_2d, scale, pscnMax, MaxCn) {
    .Call('_EstMix_calcll_1d_baf', PACKAGE = 'EstMix', lrr, nrc, baf, n_baf, lprior_f_2d, rlprior_f_2d, scale, pscnMax, MaxCn)
}

#' calculate baf for 1 normal + 2 tumors case
#' @keywords internal
#' @export
calcll_baf <- function(lrr, nrc, baf, n_baf, lprior_f_2d, rlprior_f_2d, scale, pscnMax, MaxCn) {
    .Call('_EstMix_calcll_baf', PACKAGE = 'EstMix', lrr, nrc, baf, n_baf, lprior_f_2d, rlprior_f_2d, scale, pscnMax, MaxCn)
}

#' calculate likelihood for 1 normal + 2 tumors case
#' @keywords internal
#' @export
calcll_cpp <- function(IT_new, B_new, lp, rlp, var_baf, var_tcn, scale, pscnMax, cnMax) {
    .Call('_EstMix_calcll_cpp', PACKAGE = 'EstMix', IT_new, B_new, lp, rlp, var_baf, var_tcn, scale, pscnMax, cnMax)
}

#' calculate likelihood for 1 normal + 1 tumor case
#' @keywords internal
#' @export
calcll_p1_cpp <- function(IT_new, B_new, lp, rlp, var_baf, var_tcn, scale, pscnMax, cnMax) {
    .Call('_EstMix_calcll_p1_cpp', PACKAGE = 'EstMix', IT_new, B_new, lp, rlp, var_baf, var_tcn, scale, pscnMax, cnMax)
}

#' calculate likelihood for 1 normal + 3 tumors case
#' @keywords internal
#' @export
calcll_p3 <- function(IT_new, B_new, var_baf, var_tcn, scale, pscnMax, cnMax) {
    .Call('_EstMix_calcll_p3', PACKAGE = 'EstMix', IT_new, B_new, var_baf, var_tcn, scale, pscnMax, cnMax)
}

