---
title: "Genetic Management Tools Manual"
author: "Michael Raboin, Amanda Vinson, and R. Mark Sharp"
date: "April 12, 2020"
output: 
   - rmarkdown::html_vignette
   - rmarkdown::pdf_document
   - rmarkdown::latex_document
   - rmarkdown::word_document
vignette: >
  %\VignetteEngine{knitr::knitr}
  %\VignetteIndexEntry{Genetic Management Tools Manual}
  %\usepackage[UTF-8]{inputenc}
---

[Introduction]  
[Summary of Major Functions]   
[Installation]  
[Running Shiny Application]   
[Input]    
[Pedigree Browser]   
[Genetic Value Analysis]  
[Summary Statistics]   
[Breeding Group Formation]    
[ORIP Reporting]    
[Algorithm: Breeding Group Formation]   
[Algorithm: Genome Uniqueness]   

```{r child = "manual_components/_introduction.Rmd", ref.label = "introduction"}
```
```{r child = "manual_components/_summary_of_major_functions.Rmd", ref.label = "summary-of-functions"}
```
```{r child = "manual_components/_installation.Rmd", echo = TRUE, ref.label = "gh-installation"}
```
```{r child = "manual_components/_running_shiny_application.Rmd", ref.label = "running-shiny-application"}
```
```{r child = "manual_components/_input.Rmd", ref.label = "input"}
```
```{r child = "manual_components/_pedigree_browser.Rmd", ref.label = "pedigree-browser"}
```
```{r child = "manual_components/_genetic_value_analysis.Rmd", ref.label = "genetic-value-analysis"}
```
```{r child = "manual_components/_summary_statistics.Rmd", ref.label = "summary-statistics"}
```
```{r child = "manual_components/_breeding_group_formation.Rmd", ref.label = "breeding-group-formation"}
```
```{r child = "manual_components/_gv_and_bg_desc.Rmd", ref.label = "gv-and-bg-desc"}
```
```{r child = "manual_components/_orip_reporting.Rmd", ref.label = "orip-reporting"}
```
```{r child = "manual_components/_breeding_group_algorithm.Rmd", ref.label = "breeding-group-algorithm"}
```
```{r child = "manual_components/_genome_uniqueness_algorithm.Rmd", ref.label = "genome-uniqueness-algorithm"}
```
```{r child = "manual_components/_software_development.Rmd", ref.label = "software_development"}
```

