---
title: "Using TGVE to visualize CDRC Open data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introducing tgver}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# CDRC Open Data

The first dataset is [Residential Mobility Index](https://data.cdrc.ac.uk/dataset/cdrc-residential-mobility-index). This datasets comes in two different geographies: LSOA and LAD. The data needs to be downloaded as it is behind an authentication prompt.

```{r define-tgve}
tgve = "https://tgve.github.io/app/?"
# defaultURL = "https://raw.githubusercontent.com/tgve/example-data/main/casualties_100.geojson"
# url = paste0(tgve, "defaultURL=", defaultURL)
# knitr::include_url(url)
```

```{r mobility-lsoa}
csv = readr::read_csv("vignettes/cdrc/residential-mobility-index.csv")
tgver::
```


```{r tgve-heatmap}
knitr::include_url("https://tgve.github.io/app/?defaultURL=https://raw.githubusercontent.com/tgve/example-data/main/casualties_100.geojson&layerName=heatmap")
```

