# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AAt <- function(A) {
    .Call('_expectreg_AAt', PACKAGE = 'expectreg', A)
}

AtA <- function(A) {
    .Call('_expectreg_AtA', PACKAGE = 'expectreg', A)
}

lltLS <- function(y, B, tau, lambdashort_glatt, lambdashort_orig, DD, NB, glatterms) {
    .Call('_expectreg_lltLS', PACKAGE = 'expectreg', y, B, tau, lambdashort_glatt, lambdashort_orig, DD, NB, glatterms)
}

smoothCPPP <- function(y, B, tau, lambdashort_glatt, lambdashort_orig, DD, NB, glatterms, smoothtype) {
    .Call('_expectreg_smoothCPPP', PACKAGE = 'expectreg', y, B, tau, lambdashort_glatt, lambdashort_orig, DD, NB, glatterms, smoothtype)
}

schallCPPfun <- function(glatterms, y, B, tau, lambdashort_in, DD, NB, NBP, NBPC, center) {
    .Call('_expectreg_schallCPPfun', PACKAGE = 'expectreg', glatterms, y, B, tau, lambdashort_in, DD, NB, NBP, NBPC, center)
}

