test_that("get_metadata_helpers functions work", {

    skip_if_no_cred()
    skip_if_offline()

    expect_no_error(get_categories())
    expect_no_error(get_category_combos())
    expect_no_error(get_category_option_combos())
    expect_warning(get_category_option_group_sets())
    expect_no_error(get_category_option_groups())
    expect_no_error(get_category_options())
    expect_no_error(get_data_element_group_sets())
    expect_no_error(get_data_element_groups(name %.like% '705'))
    expect_no_error(get_data_elements(name %.like% 'malaria'))
    expect_no_error(get_data_sets(name %.like% '705'))
    expect_no_error(get_user_groups())
    expect_no_error(get_indicator_group_sets())
    expect_no_error(get_indicators())
    expect_no_error(get_indicator_groups())
    expect_warning(get_option_group_sets())
    expect_no_error(get_option_groups())
    expect_no_error(get_option_sets())
    expect_no_error(get_options())
    expect_no_error(get_organisation_unit_groupsets())
    expect_no_error(get_organisation_unit_groups())
    expect_no_error(get_organisation_units())
    expect_no_error(get_organisation_unit_levels())
    expect_no_error(get_dimensions())
    expect_no_error(get_period_types())
})
