// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// firstZeroIndex
IntegerVector firstZeroIndex(NumericMatrix mat);
RcppExport SEXP _bunsen_firstZeroIndex(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(firstZeroIndex(mat));
    return rcpp_result_gen;
END_RCPP
}
// rbinom_matrix_vec
IntegerMatrix rbinom_matrix_vec(int nrows, int ncols, NumericVector probs);
RcppExport SEXP _bunsen_rbinom_matrix_vec(SEXP nrowsSEXP, SEXP ncolsSEXP, SEXP probsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nrows(nrowsSEXP);
    Rcpp::traits::input_parameter< int >::type ncols(ncolsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type probs(probsSEXP);
    rcpp_result_gen = Rcpp::wrap(rbinom_matrix_vec(nrows, ncols, probs));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bunsen_firstZeroIndex", (DL_FUNC) &_bunsen_firstZeroIndex, 1},
    {"_bunsen_rbinom_matrix_vec", (DL_FUNC) &_bunsen_rbinom_matrix_vec, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_bunsen(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
