---
title: "Breeding Group Formation"
author: "R. Mark Sharp, Ph.D."
date: "10/2/2017"
output: 
   - rmarkdown::pdf_document
   - rmarkdown::latex_document
   - rmarkdown::html_vignette
   - rmarkdown::word_document
vignette: >
  %\VignetteEngine{knitr::knitr}
  %\VignetteIndexEntry{Genetic Management Tools}
  %\usepackage[UTF-8]{inputenc}
---

## Breeding Group Formation  
The last major function of the R-package is to aid in generating breeding 
groups that avoid inter-animal relatedness. 
This tab allows you to build a number of breeding groups
from a specified list of candidate animals. 
It also has an option to build a group by
adding animals from a list of candidates to a currently-existing group.

In the top half of the tab, there are entry boxes and menus to adjust the 
options of the analysis. 
By default, the analysis will ignore relatedness between animals that is
more distant than the second cousin level, pairwise relatedness involving an 
animal under 1 year of age, and relatedness between all females. 
All of these options can be adjusted before the analysis is run, however.

If the desire is to add animals to an existing group, the IDs of the candidate 
animals can be entered into the first text box (just as they would be if a new 
group were being generated). 
The IDs of the current group members can be added into the second text box.
It should be noted that it will cause an error if the provided candidate 
animals or current group member IDs are not part of the population for 
which a genetic value analysis was run. The kinship matrix produced for this 
analysis provides the pairwise
kinship values used by the group formation functions.

After the simulation is done, the first group will be displayed automatically. 
The group being displayed can be changed with the drop-down menu. 
Whichever group is
currently being displayed can then be downloaded with the export button.

