---
title: "Genetic Value Analysis"
author: "R. Mark Sharp, Ph.D."
date: "10/2/2017"
output: 
   - rmarkdown::pdf_document
   - rmarkdown::latex_document
   - rmarkdown::html_vignette
   - rmarkdown::word_document
vignette: >
  %\VignetteEngine{knitr::knitr}
  %\VignetteIndexEntry{Genetic Management Tools}
  %\usepackage[UTF-8]{inputenc}
---
## Genetic Value Analysis  

The Genetic Value Analysis tab provides all of the options needed for producing 
a genetic value analysis report. The specifics of generating the genetic value 
analysis report are described on the ___Genetic Value Analysis and Breeding Group
Description___ tab.

When the analysis is begun, it will generate a genetic value analysis for the
currently-specified population in the pedigree. 
If no population has been specified,
the entire pedigree will go into the analysis. 
This can be problematic, as the function
for calculating the pairwise kinship matrix cannot handle large pedigrees. 
The kinship
calculation is known to handle pedigree files containing up to 6000 individuals. 
It
will not, however, handle the whole ONPRC rhesus studbook (~24,000 animals). 
The exact
maximum pedigree size is not currently known and will need to be tested. 
Due to these
problems, the input studbook will automatically be trimmed to the ancestors of 
the currently-specified population before the genetic value analysis is begun.

The genome uniqueness threshold input box allows the user to specify what 
constitutes a 'unique' allele in the gene-drop simulation. 
The algorithm description later in this document provides a more in-depth 
explanation of how the genome uniqueness calculation
uses this information. 
By default, the gene-drop simulation underlying the genome
uniqueness calculation considers an individual as unique if no other members of
the current population have inherited the same allele during an iteration of the
gene-drop. 
This can be adjusted using the drop-down box to allow up to four other animals
to have inherited the allele and still consider it unique.

After the report has been generated, it can be subset to view a specific group 
of the animals using the text input box. Both the currently-viewed subset and 
the full report can be exported to a file from here.
