---
title: "Input"
author: "R. Mark Sharp, Ph.D."
date: "10/2/2017"
output: 
   - rmarkdown::html_vignette
   - rmarkdown::pdf_document
   - rmarkdown::latex_document
   - rmarkdown::html_vignette
   - rmarkdown::word_document
vignette: >
  %\VignetteEngine{knitr::knitr}
  %\VignetteIndexEntry{Genetic Management Tools}
  %\usepackage[UTF-8]{inputenc}
---

## Input  
The Input tab is the starting point for all analyses. The file
should be a delimited, regular text file with a header row specifying the
columns. The tab provides information on the allowable columns in input
files, and how the columns will be used in quality control of the data.
Quality control of studbook data occurs automatically upon file upload.

Presently, the only columns required are those specifying the Ego ID,
Sire ID, Dam ID, and Sex. The remaining columns listed are optional,
but will be used if they are present in the uploaded file. The table
of the tab describes how these optional columns will be used. Additionally,
the panel on the left of this tab provides options that can be used during
the upload and QC process, such as specifying the field separator used in the 
uploaded file.

During quality control, a flag is added for the current, living population.
This flag is generated based on the information columns provided and is fairly
specific to how the breeding population is defined at ONPRC. Two of the options
for specifying the population of interest can be toggled through this panel,
however. Normally, the breeding colony is restricted to Indian-origin, SPF 4 animals.
These two restrictions can be turned off by setting the options on this panel.

Additionally, the population of interest can be specified directly in either
the input file, or entered on the Pedigree Browser tab.

