---
title: "Introduction"
author: "R. Mark Sharp, Ph.D."
date: "11/08/2019"
output: 
   - rmarkdown::pdf_document
   - rmarkdown::latex_document
   - rmarkdown::html_vignette
   - rmarkdown::word_document
vignette: >
  %\VignetteEngine{knitr::knitr}
  %\VignetteIndexEntry{Genetic Management Tools}
  %\usepackage[UTF-8]{inputenc}
---
## Introduction  
The goal of __nprcgenekeepr__ is to implement Genetic Tools for Colony Management.
It was initially conceived and developed as a Shiny web application at
the Oregon National Primate Research Center (ONPRC) to facilitate some of
the analyses they perform regularly.
It has been enhanced to have more capability as a Shiny application 
and to expose the functions so they can be used either interactively or in R 
scripts.

This work has been supported in part by NIH grants P51 RR13986 to the Southwest
National Primate Research Center and P51 OD011092 to the Oregon National 
Primate Research Center.

<!--It is now managed and maintained as a joint effort between ONPRC-->
<!--and Southwest National Primate Research Center (SNPRC) with the -->
<!--coding being done by R. Mark Sharp, Ph.D.-->

At present, the application supports 5 functions:

1.  Quality control of studbooks contained in text files or Excel workbooks and 
    of pedigrees within LabKey Electronic Health Records (EHR)
1.  Creation of pedigrees from a lists of animals using the LabKey EHR 
    integration
1.  Creation and display of an age by sex pyramid plot of the living animals
    within the designated pedigree
1.  Generation of Genetic Value Analysis Reports
1.  Creation of potential breeding groups with and without proscribed sex
    ratios and defined maximum kinships.



**For more information see:**  
A Practical Approach for Designing Breeding Groups to Maximize Genetic 
Diversity in a Large Colony of Captive Rhesus Macaques (*Macaca mulatto*)
Vinson, A ; Raboin, MJ
*Journal Of The American Association For Laboratory Animal Science*, 
2015 Nov, Vol.54(6), pp.700-707 [Peer Reviewed Journal]
