---
title: "Pedigree Browser"
author: "R. Mark Sharp, Ph.D."
date: "10/2/2017"
output: 
   - rmarkdown::pdf_document
   - rmarkdown::latex_document
   - rmarkdown::html_vignette
   - rmarkdown::word_document
vignette: >
  %\VignetteEngine{knitr::knitr}
  %\VignetteIndexEntry{Genetic Management Tools}
  %\usepackage[UTF-8]{inputenc}
---
## Pedigree Browser  

The Pedigree Browser tab allows the user to view the input data, specify a population
to examine, and output the cleaned studbook or trimmed pedigree.

Upon uploading a studbook file, the data goes through the quality control process
described on the Input File Format tab. The cleaned version is displayed on this tab.
By default, the entire uploaded studbook will be available for viewing on this tab.
The first 10 rows will automatically be shown, but this range can be adjusted using
the input boxes at the top. The default setting of showing only the first 10 rows
is due to the size of the full ONPRC studbook: loading all 32,000 animals can cause
the application to be slow.

The tab also contains functionality for trimming the pedigree. By checking the provided
box, the studbook that was uploaded will be trimmed down to just the ancestors of the
currently specified population. This will remove any lineages that haven't contributed
to the focal group.

As stated above, this tab will also allow the user to directly specify a population to
examine. In the top half of the tab, there is an input box to specify the focal set of
animals. The population flag can be reset by adding the desired animal IDs to the box.
Once the population flag has been set to the desired group of animals, all further
analyses will be relative to this group.

