---
title: "Software Development"
author: "R. Mark Sharp, Ph.D."
date: "2024-12-19"
output: 
   - rmarkdown::pdf_document
   - rmarkdown::latex_document
   - rmarkdown::html_vignette
   - rmarkdown::word_document
vignette: >
  %\VignetteEngine{knitr::knitr}
  %\VignetteIndexEntry{Genetic Management Tools}
  %\usepackage[UTF-8]{inputenc}
---

## Software Issues

Our goal is to use current R software development practices in an open software
environment. Users can see all of the code at [github.com/rmsharp/nprcgenekeepr](https://github.com/rmsharp/nprcgenekeepr)
and can submit suggestions and bug reports on our issue tracker at 
[github.com/rmsharp/nprcgenekeepr/issues](https://github.com/rmsharp/nprcgenekeepr/issues).

### CICD Pipeline Use

The application and associated website is being continuously integrated 
at each push to the online repository. While often new features being added
are not stable or complete, it is uncommon for the application not to run 
and perform functions that were working before. However, make sure the 
build was passing by looking for a green _R-CMD-check.yaml Passing_ badge at
the top of the README file at
[https://github.com/rmsharp/nprcgenekeepr/](https://github.com/rmsharp/nprcgenekeepr/).

### Debug Logging  

There is a logging system integrated into the package using the 
package **futile.logger**. Note the checkbox at the 
bottom of the side panel on the _Input_ tab.
When the _Debug on_ checkbox is checked (it is not checked by default), 
the application writes to a file named 
_nprcgenekeepr.log_ in the users home directory. 
Currently, events occurring the the 
_server.R_ file are logged as that is where most errors are exposed. 

### Code Coverage

Code coverage reports are part of the automated build system running in 
GitHub Actions. We are using the __testthat__ package for unit tests.
Currently all code returning values that do not access 
a database or the file system have coverage with unit tests. 
Many of these have
100 percent of the lines covered. However, the unit tests are not 
exhaustive. The practice is to add further tests as errors are detected
or when working on the code and a new unit test possibility is 
discovered. As of 20241223 95.70 percent of the lines are covered.
