object <- new("WormTensor")

# Filled by as_worm_tensor()
expect_true(is.list(object@dist_matrices))
expect_true(is.numeric(object@n_animals))
expect_true(is.character(object@union_cellnames))
expect_true(is.numeric(object@n_union_cells))
# Filled by worm_membership()
expect_equal(is(object@membership_tensor), "Tensor")
# Filled by worm_clustering()
expect_true(is.numeric(object@clustering))
expect_true(is.numeric(object@k))
expect_true(is.numeric(object@weight))
expect_true(is.numeric(object@factor))
expect_true(is.numeric(object@consensus))
# Filled by worm_evaluate()
expect_true(is.list(object@eval))
