utils::globalVariables(c("bw_alpha", "bw_gamma", "bw_beta", "bw_tau", "bw_alpha1", "bw_beta1", 
                         "bw_beta2", "hat.alpha", "CI.lower.alpha", "CI.upper.alpha",
                         "hat.gamma", "CI.lower.gamma", "CI.upper.gamma",
                         "hat.beta", "CI.lower.beta", "CI.upper.beta",
                         "hat.tau", "CI.lower.tau", "CI.upper.tau",
                         "est.M", "CI.lower", "CI.lower",
                         "med_pt", "type", "timeseq",
                         "alpha_hat", "CI.lower.a", "CI.upper.a",
                         "gamma_hat", "CI.lower.g", "CI.upper.g",
                         "beta_hat", "CI.lower.b", "CI.upper.b",
                         "tau_hat", "CI.lower.t", "CI.upper.t",
                         "medEffect", "CI.lower", "CI.upper",
                         "V2", "val",
                         "orig.mediation1", "orig.mediation2", "timeseq",
                         "hat.alpha1", "CI.lower.alpha1", "CI.upper.alpha1",
                         "hat.gamma1", "CI.lower.gamma1", "CI.upper.gamma1",
                         "hat.beta", "CI.lower.beta", "CI.upper.beta",
                         "hat.tau1", "CI.lower.tau1", "CI.upper.tau1",
                         "hat.alpha2", "CI.lower.alpha2", "CI.upper.alpha2",
                         "hat.gamma2", "CI.lower.gamma2", "CI.upper.gamma2",
                         "hat.tau2", "CI.lower.tau2", "CI.upper.tau2",
                         "hat.mediation1", "hat.mediation2"))