---
title: "Requirements"
author: Oliver Kardell
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Requirements}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Introduction

This vignette gives an overview about requirements for **flowTraceR**. The outputs of the following software applications are supported:

* Spectronaut (v15)
* MaxQuant (v2.0.3)
* DIA-NN (v1.8)
* Proteome Discoverer (v2.4)

## Spectronaut

For **flowTraceR** the following columns are required:

* PG.ProteinGroups (User Manual definition: One or several protein groups)
* EG.PrecursorId (User Manual definition: Unique Id for the precursor: [modified sequence] plus [charge])

## MaxQuant

For **flowTraceR** the following files and respective columns are required:

* evidence.txt 
    * Modified sequence (User Manual definition: Sequence representation including the post-translational modifications)
    * Charge (User Manual definition: The charge-state of the precursor ion)
    * Protein group IDs (User Manual definition: The identifier of the protein-group this redundant peptide sequence is associated with, which can be used to look up the extended protein information in the file 'proteinGroups.txt'.)
    
* proteinGroups.txt 
    * ProteinIDs (User Manual definition: Identifier(s) of protein(s) contained in the protein group)
    * id (User Manual definition: A unique (consecutive) identifier for each row in the proteinGroups table, which is used to cross-link the information in this file with the information stored in the other files.)
    
## DIA-NN

For **flowTraceR** the following columns are required:

* Precursor.Id
* Protein.Group (User Manual definition: inferred proteins) 

## Proteome Discoverer

For **flowTraceR** the following files and respective columns are required:

* PSMs.txt
    * Protein Accessions (User Manual definition: Displays the unique identifiers (accessions) of all proteins that include the given peptide sequence.)
    * Annotated Sequence (User Manual definition: Displays the names of the flanking residues of a peptide in a protein.)
    * Modifications (User Manual definition: Displays the static and dynamic modifications identified in the peptide.)
    * Charge (User Manual definition: Displays the charge state of the peptide.)

