# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393
#' Cross-Distance Matrix Calculation
#'
#' Computes the pairwise Euclidean distance between rows of two matrices.
#'
#' @param m1 Numeric matrix.
#' @param m2 Numeric matrix.
#' @return Numeric matrix of distances.
#' @export
#' @examples
#' mat1 <- matrix(1:4, ncol = 2)
#' mat2 <- matrix(5:8, ncol = 2)
#' dist_matrix <- crossdist(mat1, mat2)

crossdist <- function(m1, m2) {
    .Call(`_SCIntRuler_crossdist`, m1, m2)
}

