// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// msce_numerical
List msce_numerical(NumericMatrix t, List parameterList, int innerSteps);
RcppExport SEXP _msce_msce_numerical(SEXP tSEXP, SEXP parameterListSEXP, SEXP innerStepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type t(tSEXP);
    Rcpp::traits::input_parameter< List >::type parameterList(parameterListSEXP);
    Rcpp::traits::input_parameter< int >::type innerSteps(innerStepsSEXP);
    rcpp_result_gen = Rcpp::wrap(msce_numerical(t, parameterList, innerSteps));
    return rcpp_result_gen;
END_RCPP
}
// tsce
List tsce(NumericMatrix t, List parameterList);
RcppExport SEXP _msce_tsce(SEXP tSEXP, SEXP parameterListSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type t(tSEXP);
    Rcpp::traits::input_parameter< List >::type parameterList(parameterListSEXP);
    rcpp_result_gen = Rcpp::wrap(tsce(t, parameterList));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_msce_msce_numerical", (DL_FUNC) &_msce_msce_numerical, 3},
    {"_msce_tsce", (DL_FUNC) &_msce_tsce, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_msce(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
