# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast combn choose 2
#'
#' @param n TBD
#' @description faster combn alternative
#'
#' @export
combn_c2 <- function(n) {
    .Call(`_rENA_combn_c2`, n)
}

#' Calculate the correlations
#'
#' @param points TBD
#' @param centroids TBD
#' @param conf_level TBD
#' @description Calculate both Pearson correlations for the
#' provided points and centorids
#' @export
ena_correlation <- function(points, centroids, conf_level = 0.95) {
    .Call(`_rENA_ena_correlation`, points, centroids, conf_level)
}

#' Merge data frame columns
#' @title Merge data frame columns
#' @description TBD
#' @param df Dataframe
#' @param cols Vector
#' @param sep Character seperator
#' @export
merge_columns_c <- function(df, cols, sep = ".") {
    .Call(`_rENA_merge_columns_c`, df, cols, sep)
}

#' Upper Triangle from Vector
#'
#' @title vector to upper triangle
#' @description TBD
#' @param v [TBD]
#' @export
vector_to_ut <- function(v) {
    .Call(`_rENA_vector_to_ut`, v)
}

svector_to_ut <- function(v) {
    .Call(`_rENA_svector_to_ut`, v)
}

rows_to_co_occurrences <- function(df, binary = TRUE) {
    .Call(`_rENA_rows_to_co_occurrences`, df, binary)
}

ref_window_df <- function(df, windowSize = 1, windowForward = 0, binary = TRUE) {
    .Call(`_rENA_ref_window_df`, df, windowSize, windowForward, binary)
}

ref_window_lag <- function(df, windowSize = 0L, binary = TRUE) {
    .Call(`_rENA_ref_window_lag`, df, windowSize, binary)
}

#' Sphere norm
#' @title Sphere norm
#' @description TBD
#' @param dfM Dataframe
#' @export
fun_sphere_norm <- function(dfM) {
    .Call(`_rENA_fun_sphere_norm`, dfM)
}

#' Non sphere norm
#'
#' @title Non sphere norm
#' @description TBD
#' @param dfM Dataframe
#' @export
fun_skip_sphere_norm <- function(dfM) {
    .Call(`_rENA_fun_skip_sphere_norm`, dfM)
}

center_data_c <- function(values) {
    .Call(`_rENA_center_data_c`, values)
}

triIndices <- function(len, row = -1L) {
    .Call(`_rENA_triIndices`, len, row)
}

lws_lsq_positions <- function(adjMats, t, numDims) {
    .Call(`_rENA_lws_lsq_positions`, adjMats, t, numDims)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_rENA_RcppExport_registerCCallable`)
})
