#! /bin/bash

sed -i 's/"algorithms.h"/"coretools\/algorithms.h"/g' $1
sed -i 's/"TBitSet.h"/"coretools\/Containers\/TBitSet.h"/g' $1
sed -i 's/"TDualArray.h"/"coretools\/Containers\/TDualArray.h"/g' $1
sed -i 's/"TDualStrongArray.h"/"coretools\/Containers\/TDualStrongArray.h"/g' $1
sed -i 's/"TMassFunction.h"/"coretools\/Containers\/TMassFunction.h"/g' $1
sed -i 's/"TShortVector.h"/"coretools\/Containers\/TShortVector.h"/g' $1
sed -i 's/"TStrongArray.h"/"coretools\/Containers\/TStrongArray.h"/g' $1
sed -i 's/"devtools.h"/"coretools\/devtools.h"/g' $1
sed -i 's/"enum.h"/"coretools\/enum.h"/g' $1
sed -i 's/"gzstream.h"/"coretools\/Files\/gzstream.h"/g' $1
sed -i 's/"TCompare.h"/"coretools\/Files\/TCompare.h"/g' $1
sed -i 's/"TFile.h"/"coretools\/Files\/TFile.h"/g' $1
sed -i 's/"TOutputFile.h"/"coretools\/Files\/TOutputFile.h"/g' $1
sed -i 's/"TTest.h"/"coretools\/IntegrationTests\/TTest.h"/g' $1
sed -i 's/"TTesting.h"/"coretools\/IntegrationTests\/TTesting.h"/g' $1
sed -i 's/"TTestList.h"/"coretools\/IntegrationTests\/TTestList.h"/g' $1
sed -i 's/"globalConstants.h"/"coretools\/Main\/globalConstants.h"/g' $1
sed -i 's/"progressTools.h"/"coretools\/Main\/progressTools.h"/g' $1
sed -i 's/"TError.h"/"coretools\/Main\/TError.h"/g' $1
sed -i 's/"TLog.h"/"coretools\/Main\/TLog.h"/g' $1
sed -i 's/"TMain.h"/"coretools\/Main\/TMain.h"/g' $1
sed -i 's/"TParameters.h"/"coretools\/Main\/TParameters.h"/g' $1
sed -i 's/"TRandomGenerator.h"/"coretools\/Main\/TRandomGenerator.h"/g' $1
sed -i 's/"TTask.h"/"coretools\/Main\/TTask.h"/g' $1
sed -i 's/"TTaskList.h"/"coretools\/Main\/TTaskList.h"/g' $1
sed -i 's/"counters.h"/"coretools\/Math\/counters.h"/g' $1
sed -i 's/"mathConstants.h"/"coretools\/Math\/mathConstants.h"/g' $1
sed -i 's/"mathFunctions.h"/"coretools\/Math\/mathFunctions.h"/g' $1
sed -i 's/"TCategoricalDistribution.h"/"coretools\/Math\/TCategoricalDistribution.h"/g' $1
sed -i 's/"TLogZeroOneLookup.h"/"coretools\/Math\/TLogZeroOneLookup.h"/g' $1
sed -i 's/"TMatrix.h"/"coretools\/Math\/TMatrix.h"/g' $1
sed -i 's/"TNumericRange.h"/"coretools\/Math\/TNumericRange.h"/g' $1
sed -i 's/"TProbabilityDistributions.h"/"coretools\/Math\/TProbabilityDistributions.h"/g' $1
sed -i 's/"TSubsamplePicker.h"/"coretools\/Math\/TSubsamplePicker.h"/g' $1
sed -i 's/"TSumLog.h"/"coretools\/Math\/TSumLog.h"/g' $1
sed -i 's/"memoize.h"/"coretools\/memoize.h"/g' $1
sed -i 's/"TDataFile.h"/"coretools\/Storage\/TDataFile.h"/g' $1
sed -i 's/"TDataFileNames.h"/"coretools\/Storage\/TDataFileNames.h"/g' $1
sed -i 's/"TDimension.h"/"coretools\/Storage\/TDimension.h"/g' $1
sed -i 's/"TNames.h"/"coretools\/Storage\/TNames.h"/g' $1
sed -i 's/"TStorage.h"/"coretools\/Storage\/TStorage.h"/g' $1
sed -i 's/"fromString.h"/"coretools\/Strings\/fromString.h"/g' $1
sed -i 's/"lazy.h"/"coretools\/Strings\/lazy.h"/g' $1
sed -i 's/"stringFunctions.h"/"coretools\/Strings\/stringFunctions.h"/g' $1
sed -i 's/"toString.h"/"coretools\/Strings\/toString.h"/g' $1
sed -i 's/"traits.h"/"coretools\/traits.h"/g' $1
sed -i 's/"TTimer.h"/"coretools\/TTimer.h"/g' $1
sed -i 's/"commonWeakTypes.h"/"coretools\/Types\/commonWeakTypes.h"/g' $1
sed -i 's/"probability.h"/"coretools\/Types\/probability.h"/g' $1
sed -i 's/"strongTypes.h"/"coretools\/Types\/strongTypes.h"/g' $1
sed -i 's/"weakTypes.h"/"coretools\/Types\/weakTypes.h"/g' $1
sed -i 's/"weakTypesWithLogExp.h"/"coretools\/Types\/weakTypesWithLogExp.h"/g' $1
