library(tind)
(nw <- now())
year(nw)
quarter(nw)
month(nw)
month(nw, labels = TRUE)
week(nw)
day(nw)
day_of_week(nw)
day_of_week(nw, labels = TRUE)
day_of_year(nw)
hour(nw)
am(nw)
pm(nw)
minute(nw)
second(nw)
is.leap_year(nw)
days_in_year(nw)
weeks_in_year(nw)
days_in_quarter(nw)
days_in_month(nw)
hours_in_day(nw)
is.dst(nw)
as.date(nw)
as.time(nw)
date_time_split(nw)
as.week(nw)
as.month(nw)
as.quarter(nw)
as.year(nw)
calendar()

## For a comprehensive introduction to tind package please read package vignettes:
## 'indices' - Working with Different Types of Time Indices Using `tind` Class
## 'calendar' - Calendrical Computations Using `tind` Package

