int tri(int x);
int ceili(double x);
int mycol(int x);
int myrow(int x);
int findMin(double *dist, int lb, int ub, int mmn);
int levelTwoCheck(int i, int j, int *l1names);
int findMin2(double *dist, int ncol, int i);
double * eliminate(int i, double *vec, int nrow);
int cmpfunc(int a, int b);
int getElem(int x, int y);
double maxDist(double *dist, unsigned int *matches, int num);
double * eliminatePairDist(int i, int j, double *vec);
