#ifndef _rxrandom_defines_h__
#define _rxrandom_defines_h__
#ifdef _isrxode2random_
#define rxbinom rxode2random_rxbinom
#define rxnbinomMu rxode2random_rxnbinomMu
#define rxnbinom rxode2random_rxnbinom
#define rxcauchy rxode2random_rxcauchy
#define rxchisq rxode2random_rxchisq
#define rxexp rxode2random_rxexp
#define rxf rxode2random_rxf
#define rxgeom rxode2random_rxgeom
#define rxnorm rxode2random_rxnorm
#define rxpois rxode2random_rxpois
#define rxt_ rxode2random_rxt_
#define rxunif rxode2random_rxunif
#define rxweibull rxode2random_rxweibull
#define rxgamma rxode2random_rxgamma
#define rxbeta rxode2random_rxbeta
#define rxnormV rxode2random_rxnormV
#define ribinom rxode2random_ribinom
#define rinbinomMu rxode2random_rinbinomMu
#define rinbinom rxode2random_rinbinom
#define ricauchy rxode2random_ricauchy
#define richisq rxode2random_richisq
#define riexp rxode2random_riexp
#define rif rxode2random_rif
#define rigeom rxode2random_rigeom
#define rinorm rxode2random_rinorm
#define ripois rxode2random_ripois
#define rit_ rxode2random_rit_
#define riunif rxode2random_riunif
#define riweibull rxode2random_riweibull
#define rigamma rxode2random_rigamma
#define ribeta rxode2random_ribeta
#define rinormV rxode2random_rinormV
#define qassertS _rxode2random_qassertS
#define qtest _rxode2random_qtest
#define qstrictS _rxode2random_qstrictS
#define qstrictSn _rxode2random_qstrictSn
#define qstrictSdn _rxode2random_qstrictSdn
#define qstrict _rxode2random_qstrict
#define rx_global rxode2random_rx_global
#define op_global rxode2random_op_global
#define getLowerVec rxode2random_getLowerVec
#define getUpperVec rxode2random_getUpperVec
#define getArmaMat  rxode2random_getArmaMat
#define getLowerVecSexp rxode2random_getLowerVecSexp
#define getUpperVecSexp rxode2random_getUpperVecSexp
#define getArmaMatSexp  rxode2random_getArmaMatSexp
#define setZeroMatrix rxode2random_setZeroMatrix
#define rxSolveFree rxode2random_rxSolveFree
#define etTransSexp rxode2random_etTransSexp
#define _vecDF _rxode2random_vecDF
#define rxModelsAssign roxde2random_rxModelsAssign
#define rxRmvnSEXP rxode2random_rxRmvnSEXP
#define rxModelVars_ rxode2random_rxModelVars_
#define chin rxode2random_chin
#define rxExpandNestingSexp rxode2random_rxExpandNestingSexp
#define rxSeedEng rxode2random_rxSeedEng
#define _rxSetSeed rxode2random_rxSetSeed
#define rxGetSeed rxode2random_rxGetSeed
#define _cbindOme _rxode2random_cbindOme
#define convertId_ rxode2random_convertId_
#define getRxSeed1 _rxode2random_getRxSeed1
#define setRxSeedFinal _rxode2random_setRxSeedFinal
#define setSeedEng1 _rxode2random_setSeedEng1
#define seedEng _rxode2random_seedEng
#endif // _isrxode2random_

#endif
