context("BP_estim")
set.seed(410)
x=pb_sim(100, 0.5, "none", d1=0, d2=1, mean=0, var=1)
expect_error(BP_estim(x,trend="limear"))
expect_error(BP_estim(x,tau=0))
expect_error(BP_estim(x,tau=2))
expect_error(BP_estim(x,type="SK"))
expect_error(BP_estim(x,m=100,type="LKT"))
expect_error(BP_estim(x,type="MR",serial="x"))
expect_error(BP_estim(x,direction="11"))
expect_warning(BP_estim(x,d_bw=0.4))
expect_error(BP_estim(x,d_bw=0))
expect_error(BP_estim(x,d_bw=1.5))
x=stats::ts(x)
expect_error(BP_estim(x))
x=matrix(1:100,ncol=2)
expect_error(BP_estim(x))
x=pb_sim(100, 0.5, "none", d1=0, d2=1, mean=0, var=1)
mod=BP_estim(x)
expect_gt(mod$Breakpoint,0)
expect_lt(mod$Breakpoint,100)
expect_true(is.vector(mod))
expect_gt(mod$sd_1,0)
expect_gt(mod$sd_2,0)
mod=BP_estim(x,d_estim="ELW")
expect_gt(mod$sd_1,0)
expect_gt(mod$sd_2,0)
