# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

checkSZ <- function(Data_to_check, h) {
    .Call('_NestedCategBayesImpute_checkSZ', PACKAGE = 'NestedCategBayesImpute', Data_to_check, h)
}

checkSZ2 <- function(Data_to_check, h) {
    .Call('_NestedCategBayesImpute_checkSZ2', PACKAGE = 'NestedCategBayesImpute', Data_to_check, h)
}

checkconstraints_HHhead_at_group_level <- function(data, neededpossiblehh, hh_size, parallel) {
    .Call('_NestedCategBayesImpute_checkconstraints_HHhead_at_group_level', PACKAGE = 'NestedCategBayesImpute', data, neededpossiblehh, hh_size, parallel)
}

checkconstraints <- function(data, neededpossiblehh, hh_size) {
    .Call('_NestedCategBayesImpute_checkconstraints', PACKAGE = 'NestedCategBayesImpute', data, neededpossiblehh, hh_size)
}

GetImpossibleHouseholds <- function(d, n_star_h, lambda, omega, phi, pi, blocksize, n, synindex, HHhead_at_group_level, Parallel) {
    .Call('_NestedCategBayesImpute_GetImpossibleHouseholds', PACKAGE = 'NestedCategBayesImpute', d, n_star_h, lambda, omega, phi, pi, blocksize, n, synindex, HHhead_at_group_level, Parallel)
}

groupcount <- function(g1, g2, n1, n2) {
    .Call('_NestedCategBayesImpute_groupcount', PACKAGE = 'NestedCategBayesImpute', g1, g2, n1, n2)
}

groupcount1D <- function(g, n) {
    .Call('_NestedCategBayesImpute_groupcount1D', PACKAGE = 'NestedCategBayesImpute', g, n)
}

UpdateBeta <- function(ba, bb, v) {
    .Call('_NestedCategBayesImpute_UpdateBeta', PACKAGE = 'NestedCategBayesImpute', ba, bb, v)
}

UpdateAlpha <- function(aa, ab, u) {
    .Call('_NestedCategBayesImpute_UpdateAlpha', PACKAGE = 'NestedCategBayesImpute', aa, ab, u)
}

sampleG <- function(phi, data, omega, pi, ni, HHdata, lambda, Parallel) {
    .Call('_NestedCategBayesImpute_sampleG', PACKAGE = 'NestedCategBayesImpute', phi, data, omega, pi, ni, HHdata, lambda, Parallel)
}

households2individuals <- function(data, hh_size) {
    .Call('_NestedCategBayesImpute_households2individuals', PACKAGE = 'NestedCategBayesImpute', data, hh_size)
}

samplehouseholds <- function(phi, omega, pi, d, lambda, currrentbatch, nHouseholds, householdsize, HeadAtGroupLevel, Parallel) {
    .Call('_NestedCategBayesImpute_samplehouseholds', PACKAGE = 'NestedCategBayesImpute', phi, omega, pi, d, lambda, currrentbatch, nHouseholds, householdsize, HeadAtGroupLevel, Parallel)
}

UpdateLambda <- function(HHdata_all, G_all, dHH, FF) {
    .Call('_NestedCategBayesImpute_UpdateLambda', PACKAGE = 'NestedCategBayesImpute', HHdata_all, G_all, dHH, FF)
}

UpdateLambdaWeighted <- function(HHdata_all, G_all, dHH, FF, struc_weight) {
    .Call('_NestedCategBayesImpute_UpdateLambdaWeighted', PACKAGE = 'NestedCategBayesImpute', HHdata_all, G_all, dHH, FF, struc_weight)
}

sampleM <- function(phi, data, omega, G, serial, Parallel) {
    .Call('_NestedCategBayesImpute_sampleM', PACKAGE = 'NestedCategBayesImpute', phi, data, omega, G, serial, Parallel)
}

SampleMissing <- function(MissData, para, orig, G_household, M, hyper) {
    .Call('_NestedCategBayesImpute_SampleMissing', PACKAGE = 'NestedCategBayesImpute', MissData, para, orig, G_household, M, hyper)
}

UpdateOmega <- function(beta, M_all, FF, SS) {
    .Call('_NestedCategBayesImpute_UpdateOmega', PACKAGE = 'NestedCategBayesImpute', beta, M_all, FF, SS)
}

UpdateOmegaWeighted <- function(beta, M_all, FF, SS, struc_weight) {
    .Call('_NestedCategBayesImpute_UpdateOmegaWeighted', PACKAGE = 'NestedCategBayesImpute', beta, M_all, FF, SS, struc_weight)
}

UpdatePhi <- function(data, M_all, FF, SS, d, maxd) {
    .Call('_NestedCategBayesImpute_UpdatePhi', PACKAGE = 'NestedCategBayesImpute', data, M_all, FF, SS, d, maxd)
}

UpdatePhiWeighted <- function(data, M_all, FF, SS, d, maxd, struc_weight) {
    .Call('_NestedCategBayesImpute_UpdatePhiWeighted', PACKAGE = 'NestedCategBayesImpute', data, M_all, FF, SS, d, maxd, struc_weight)
}

UpdatePi <- function(alpha, G_all, FF) {
    .Call('_NestedCategBayesImpute_UpdatePi', PACKAGE = 'NestedCategBayesImpute', alpha, G_all, FF)
}

UpdatePiWeighted <- function(alpha, G_all, FF, struc_weight) {
    .Call('_NestedCategBayesImpute_UpdatePiWeighted', PACKAGE = 'NestedCategBayesImpute', alpha, G_all, FF, struc_weight)
}

