include $(R_HOME)/etc/i386/Makeconf 
BUGS_PATH = `"${R_HOME}/bin${R_ARCH_BIN}/Rscript" -e "source('../R/windows/findOpenBUGS.R');cat(findOpenBUGS()[['dir']])"`
BUGS_LIBS = "$(BUGS_PATH)/libOpenBUGS.dll"
BUGS_LDFLAGS = -m32 -Wl,-rpath="$(BUGS_PATH)"

BugsHelper:
	mkdir -p $(R_PACKAGE_DIR)/exec
	$(CC) $(CFLAGS) $(LDFLAGS) $(BUGS_LDFLAGS) BugsHelper.c $(BUGS_LIBS) -o $(R_PACKAGE_DIR)/exec/BugsHelper
