# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

houghStemPoints <- function(las, h1 = 1, h2 = 3, hstep = 0.5, radius = 0.25, pixel = 0.025, density = 0.1, votes = 3L) {
    .Call(`_CrownScorchTLS_houghStemPoints`, las, h1, h2, hstep, radius, pixel, density, votes)
}

houghStemPlot <- function(las, ptIds, h1 = 1, h2 = 3, hstep = 0.5, radius = 0.25, pixel = 0.025, density = 0.1, votes = 3L) {
    .Call(`_CrownScorchTLS_houghStemPlot`, las, ptIds, h1, h2, hstep, radius, pixel, density, votes)
}

