// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ChangePointAnalyzeNorm
NumericMatrix ChangePointAnalyzeNorm(NumericVector Data, IntegerVector InputLength, IntegerVector MaxJump, NumericVector Prior);
RcppExport SEXP StepSignalMargiLike_ChangePointAnalyzeNorm(SEXP DataSEXP, SEXP InputLengthSEXP, SEXP MaxJumpSEXP, SEXP PriorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Data(DataSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type InputLength(InputLengthSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type MaxJump(MaxJumpSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Prior(PriorSEXP);
    rcpp_result_gen = Rcpp::wrap(ChangePointAnalyzeNorm(Data, InputLength, MaxJump, Prior));
    return rcpp_result_gen;
END_RCPP
}
// ChangePointAnalyzeNormUnRes
NumericVector ChangePointAnalyzeNormUnRes(NumericVector Data, IntegerVector InputLength, NumericVector Prior);
RcppExport SEXP StepSignalMargiLike_ChangePointAnalyzeNormUnRes(SEXP DataSEXP, SEXP InputLengthSEXP, SEXP PriorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Data(DataSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type InputLength(InputLengthSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Prior(PriorSEXP);
    rcpp_result_gen = Rcpp::wrap(ChangePointAnalyzeNormUnRes(Data, InputLength, Prior));
    return rcpp_result_gen;
END_RCPP
}
// ChangePointAnalyzePoiss
NumericMatrix ChangePointAnalyzePoiss(NumericVector Data, IntegerVector InputLength, IntegerVector MaxJump, NumericVector Prior);
RcppExport SEXP StepSignalMargiLike_ChangePointAnalyzePoiss(SEXP DataSEXP, SEXP InputLengthSEXP, SEXP MaxJumpSEXP, SEXP PriorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Data(DataSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type InputLength(InputLengthSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type MaxJump(MaxJumpSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Prior(PriorSEXP);
    rcpp_result_gen = Rcpp::wrap(ChangePointAnalyzePoiss(Data, InputLength, MaxJump, Prior));
    return rcpp_result_gen;
END_RCPP
}
// ChangePointAnalyzePoissUnRes
NumericVector ChangePointAnalyzePoissUnRes(NumericVector Data, IntegerVector InputLength, NumericVector Prior);
RcppExport SEXP StepSignalMargiLike_ChangePointAnalyzePoissUnRes(SEXP DataSEXP, SEXP InputLengthSEXP, SEXP PriorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Data(DataSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type InputLength(InputLengthSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Prior(PriorSEXP);
    rcpp_result_gen = Rcpp::wrap(ChangePointAnalyzePoissUnRes(Data, InputLength, Prior));
    return rcpp_result_gen;
END_RCPP
}
