#  `r input$biomarkerReportTitle`
-----

### Step 1. `r stepsTableInitial[1, "SteppingStone"]`:

- `r stepsTableInitial[1,"Question"]`

`r ClinicalScenario`. 



### Step 2.  `r stepsTableInitial[2, "SteppingStone"]` :

- `r stepsTableInitial[2,"Question"]`

The biomarker is intended to help `r input$who`,
by identifying who should receive 
**`r input$Option_Treat`** and who should receive **`r input$Option_Wait`**.


### Step 3. `r stepsTableInitial[3, "SteppingStone"]`:

- `r stepsTableInitial[3,"Question"]`

Currently, the proportion of patients who should receive prevalence is *number needed to treat* to help one (*NNT*) is 
The biomarker test will be useful can create a clinical
consensus supporting using the test for clinical decisions. 
if the NNT among test-positive patients, *NNT<sub>Pos</sub>*, is less than *NNT<sub>Lower</sub>*  = `r NNTlower`, 
and 
if the NNT among test-negative patients, *NNT<sub>Neg</sub>*, is greater than *NNT<sub>Upper</sub>*  = `r NNTupper`.

Therefore we choose targets *NNT<sub>Pos</sub>* = `r input$NNTpos`  and  *NNT<sub>Neg</sub>* = `r input$NNTneg`.
This performance should suffice to create a clinical
consensus supporting using the test for clinical decisions.
These values correspond to *positive predictive value = PPV* = `r 1/input$NNTpos`, 
and *negative predictive value = NPV* = `r 1-1/input$NNTneg`.

### Step 4.  `r stepsTableInitial[4, "SteppingStone"]`:

- `r stepsTableInitial[4,"Question"]`

If the biomarker test achieves these predictive values,
the benefit to patients will be `r input$SpecificBenefit`.  

### Step 5. `r stepsTableInitial[5, "SteppingStone"]`:

- `r stepsTableInitial[5, "Question"]`

The retrospective study will 
recruit `r input$NpatientsProspective` patients.
`r input$follow_up`. 
If the test divides the `r input$NpatientsProspective` 
patients into roughly 
`r input$percentPositive`% positive and 
`r 100 - input$percentPositive`% negative, 
and if the estimates
match the hoped-for values 
*NNT<sub>Pos</sub>* = `r input$NNTpos`  and  *NNT<sub>Neg</sub>* = `r input$NNTneg`, 
then the confidence intervals would be
(`r round(digits=3, rValues$PPV_ProspectiveInterval)`) for *PPV*, and 
(`r round(digits=3, rValues$NPV_ProspectiveInterval)`) for *NPV*, or equivalently
(`r round(digits=3, rValues$NNTpos_ProspectiveInterval)`)  for *NNT<sub>Pos</sub>*, and 
(`r round(digits=3, rValues$NNTneg_ProspectiveInterval)`) for *NNT<sub>Neg</sub>*. 

`r input$ProspectiveStudyNotes`

### Step 6. `r stepsTableInitial[6, "SteppingStone"]`:

- `r stepsTableInitial[6,"Question"]`


The proportion of patients `r input$BestToTreatDescription` is assumed to be 
`r round(100*input$prevalence)`%.
Combining that with the target *PPV* and
*NPV*, the required
sensitivity (*SN*) and specificity (*SP*) are `r rValues$sensitivityPercent`% and `r rValues$specificityPercent`%,
respectively (contra-Bayes Theorem). 
To get a sense of the accuracy of
anticipated estimates in the retrospective (case/control) portion of the
study, we consider anticipated results for samples sizes `r input$samplesizeCases` cases 
and `r input$samplesizeControls`
controls. For example, if the estimates 
*SN* = `r round(input$samplesizeCases* rValues$sensitivity)`/`r input$samplesizeCases` 
=  `r round(100*input$samplesizeCases* rValues$sensitivity/input$samplesizeCases)` % and
*SP* = `r round(input$samplesizeControls* rValues$specificity)`/`r input$samplesizeControls` 
=  `r round(100*input$samplesizeControls* rValues$specificity/input$samplesizeControls)`  % 
are observed, then the corresponding confidence intervals
will be 
(`r round(digits=3, rValues$Se_RetrospectiveInterval)`)
for *SN*, and 
(`r round(digits=3, rValues$Sp_RetrospectiveInterval)`)
for *SP*.
For *NNT<sub>Pos</sub>* and for *NNT<sub>Neg</sub>*,
the Bayes predictive
intervals will be 
(`r round(digits=3, rValues$NNTpos_RetrospectiveInterval)`)
for *NNT<sub>Pos</sub>* , and 
(`r round(digits=3, rValues$NNTneg_RetrospectiveInterval)`)
for *NNT<sub>Neg</sub>* . 
(These predictive intervals derive from assuming independent Jeffreys
priors for *SN* and *SP*, sampling from joint independent posteriors
incorporating the anticipated results, and applying Bayes theorem).
