on:
  push:
    paths:
      - .github/workflows/update.yml
      - update.R
  schedule:
    ## Run once an hour
    - cron:  '0 * * * *'

name: update

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - name: Install R dependencies
        run: |
          install.packages("jsonlite")
        shell: Rscript {0}
      - name: Check CLI
        run: |
          Rscript update.R
          ls -al
